// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: artifacts.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Smidr.V1 {
  /// <summary>
  /// ArtifactService manages artifacts associated with builds.
  /// </summary>
  public static partial class ArtifactService
  {
    static readonly string __ServiceName = "smidr.v1.ArtifactService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Smidr.V1.ListArtifactsRequest> __Marshaller_smidr_v1_ListArtifactsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Smidr.V1.ListArtifactsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Smidr.V1.ListArtifactsResponse> __Marshaller_smidr_v1_ListArtifactsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Smidr.V1.ListArtifactsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Smidr.V1.GetArtifactRequest> __Marshaller_smidr_v1_GetArtifactRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Smidr.V1.GetArtifactRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Smidr.V1.ArtifactSummary> __Marshaller_smidr_v1_ArtifactSummary = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Smidr.V1.ArtifactSummary.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Smidr.V1.DownloadArtifactRequest> __Marshaller_smidr_v1_DownloadArtifactRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Smidr.V1.DownloadArtifactRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Smidr.V1.DownloadArtifactResponse> __Marshaller_smidr_v1_DownloadArtifactResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Smidr.V1.DownloadArtifactResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Smidr.V1.DeleteArtifactRequest> __Marshaller_smidr_v1_DeleteArtifactRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Smidr.V1.DeleteArtifactRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Smidr.V1.DeleteArtifactResponse> __Marshaller_smidr_v1_DeleteArtifactResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Smidr.V1.DeleteArtifactResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Smidr.V1.ListArtifactsRequest, global::Smidr.V1.ListArtifactsResponse> __Method_ListArtifacts = new grpc::Method<global::Smidr.V1.ListArtifactsRequest, global::Smidr.V1.ListArtifactsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListArtifacts",
        __Marshaller_smidr_v1_ListArtifactsRequest,
        __Marshaller_smidr_v1_ListArtifactsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Smidr.V1.GetArtifactRequest, global::Smidr.V1.ArtifactSummary> __Method_GetArtifact = new grpc::Method<global::Smidr.V1.GetArtifactRequest, global::Smidr.V1.ArtifactSummary>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetArtifact",
        __Marshaller_smidr_v1_GetArtifactRequest,
        __Marshaller_smidr_v1_ArtifactSummary);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Smidr.V1.DownloadArtifactRequest, global::Smidr.V1.DownloadArtifactResponse> __Method_DownloadArtifact = new grpc::Method<global::Smidr.V1.DownloadArtifactRequest, global::Smidr.V1.DownloadArtifactResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DownloadArtifact",
        __Marshaller_smidr_v1_DownloadArtifactRequest,
        __Marshaller_smidr_v1_DownloadArtifactResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Smidr.V1.DeleteArtifactRequest, global::Smidr.V1.DeleteArtifactResponse> __Method_DeleteArtifact = new grpc::Method<global::Smidr.V1.DeleteArtifactRequest, global::Smidr.V1.DeleteArtifactResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteArtifact",
        __Marshaller_smidr_v1_DeleteArtifactRequest,
        __Marshaller_smidr_v1_DeleteArtifactResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Smidr.V1.ArtifactsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ArtifactService</summary>
    [grpc::BindServiceMethod(typeof(ArtifactService), "BindService")]
    public abstract partial class ArtifactServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Smidr.V1.ListArtifactsResponse> ListArtifacts(global::Smidr.V1.ListArtifactsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Smidr.V1.ArtifactSummary> GetArtifact(global::Smidr.V1.GetArtifactRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Smidr.V1.DownloadArtifactResponse> DownloadArtifact(global::Smidr.V1.DownloadArtifactRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Smidr.V1.DeleteArtifactResponse> DeleteArtifact(global::Smidr.V1.DeleteArtifactRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ArtifactService</summary>
    public partial class ArtifactServiceClient : grpc::ClientBase<ArtifactServiceClient>
    {
      /// <summary>Creates a new client for ArtifactService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ArtifactServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ArtifactService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ArtifactServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ArtifactServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ArtifactServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Smidr.V1.ListArtifactsResponse ListArtifacts(global::Smidr.V1.ListArtifactsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListArtifacts(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Smidr.V1.ListArtifactsResponse ListArtifacts(global::Smidr.V1.ListArtifactsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListArtifacts, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Smidr.V1.ListArtifactsResponse> ListArtifactsAsync(global::Smidr.V1.ListArtifactsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListArtifactsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Smidr.V1.ListArtifactsResponse> ListArtifactsAsync(global::Smidr.V1.ListArtifactsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListArtifacts, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Smidr.V1.ArtifactSummary GetArtifact(global::Smidr.V1.GetArtifactRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetArtifact(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Smidr.V1.ArtifactSummary GetArtifact(global::Smidr.V1.GetArtifactRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetArtifact, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Smidr.V1.ArtifactSummary> GetArtifactAsync(global::Smidr.V1.GetArtifactRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetArtifactAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Smidr.V1.ArtifactSummary> GetArtifactAsync(global::Smidr.V1.GetArtifactRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetArtifact, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Smidr.V1.DownloadArtifactResponse DownloadArtifact(global::Smidr.V1.DownloadArtifactRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DownloadArtifact(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Smidr.V1.DownloadArtifactResponse DownloadArtifact(global::Smidr.V1.DownloadArtifactRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DownloadArtifact, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Smidr.V1.DownloadArtifactResponse> DownloadArtifactAsync(global::Smidr.V1.DownloadArtifactRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DownloadArtifactAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Smidr.V1.DownloadArtifactResponse> DownloadArtifactAsync(global::Smidr.V1.DownloadArtifactRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DownloadArtifact, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Smidr.V1.DeleteArtifactResponse DeleteArtifact(global::Smidr.V1.DeleteArtifactRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteArtifact(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Smidr.V1.DeleteArtifactResponse DeleteArtifact(global::Smidr.V1.DeleteArtifactRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteArtifact, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Smidr.V1.DeleteArtifactResponse> DeleteArtifactAsync(global::Smidr.V1.DeleteArtifactRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteArtifactAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Smidr.V1.DeleteArtifactResponse> DeleteArtifactAsync(global::Smidr.V1.DeleteArtifactRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteArtifact, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ArtifactServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ArtifactServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ArtifactServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ListArtifacts, serviceImpl.ListArtifacts)
          .AddMethod(__Method_GetArtifact, serviceImpl.GetArtifact)
          .AddMethod(__Method_DownloadArtifact, serviceImpl.DownloadArtifact)
          .AddMethod(__Method_DeleteArtifact, serviceImpl.DeleteArtifact).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ArtifactServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ListArtifacts, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Smidr.V1.ListArtifactsRequest, global::Smidr.V1.ListArtifactsResponse>(serviceImpl.ListArtifacts));
      serviceBinder.AddMethod(__Method_GetArtifact, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Smidr.V1.GetArtifactRequest, global::Smidr.V1.ArtifactSummary>(serviceImpl.GetArtifact));
      serviceBinder.AddMethod(__Method_DownloadArtifact, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Smidr.V1.DownloadArtifactRequest, global::Smidr.V1.DownloadArtifactResponse>(serviceImpl.DownloadArtifact));
      serviceBinder.AddMethod(__Method_DeleteArtifact, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Smidr.V1.DeleteArtifactRequest, global::Smidr.V1.DeleteArtifactResponse>(serviceImpl.DeleteArtifact));
    }

  }
}
#endregion
