package init

import (
	"fmt"
	"log/slog"
	"os"

	"github.com/schererja/smidr/pkg/logger"
	"github.com/spf13/cobra"
)

var log *logger.Logger

var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a new Smidr project configuration",
	Long: `Initialize a new Smidr project by generating a template configuration file (smidr.yaml) in the current directory.

If a project name is provided, it will be used in the generated config. If not, 'my-smidr-project' is used by default.

This command will not overwrite an existing smidr.yaml file.`,
	Example: `  smidr init
  smidr init myproject
  smidr init "Acme IoT Gateway"`,
	Args: cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		projectName := "my-smidr-project"
		if len(args) == 1 {
			projectName = args[0]
		}
		if err := initProject(projectName); err != nil {
			log.Error("Error initializing project", err)
			return
		}
	},
}

// New returns the init command for registration with the root command
func New(logger *logger.Logger) *cobra.Command {
	log = logger
	return initCmd
}

func initProject(projectName string) error {
	configPath := "config.yaml"
	if _, err := os.Stat("config.yaml"); err == nil {
		return fmt.Errorf("configuration file %s already exists", configPath)
	}

	// Create the template file
	template := generateConfigTemplate(projectName)
	if err := os.WriteFile(configPath, []byte(template), 0644); err != nil {
		return fmt.Errorf("failed to write configuration file: %w", err)
	}
	log.Info("Initialized Smidr project", slog.String("projectName", projectName))
	log.Info("Edit config.yaml to configure your build")
	log.Info("Run 'smidr build' to start building")
	return nil
}

func generateConfigTemplate(projectName string) string {
	return fmt.Sprintf(`# Smidr Build Configuration
# Generated by 'smidr init %s'

name: %s
description: "Smidr Control Plane Project"
version: "0.1.0"
serverConfig:
  port: "50051" # Host and port for the Smidr Control Plane server
  address: "0.0.0.0" # Address for the Smidr daemon to listen on

`, projectName, projectName)
}
