// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: artifacts.proto

package smidrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListArtifactsRequest is used to request a list of artifacts for an build.
type ListArtifactsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuildIdentifier *BuildIdentifier       `protobuf:"bytes,1,opt,name=build_identifier,json=buildIdentifier,proto3" json:"build_identifier,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_artifacts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{0}
}

func (x *ListArtifactsRequest) GetBuildIdentifier() *BuildIdentifier {
	if x != nil {
		return x.BuildIdentifier
	}
	return nil
}

// ListArtifactsResponse contains a list of artifacts associated with a build.
type ListArtifactsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Artifacts       []*ArtifactSummary     `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	BuildIdentifier *BuildIdentifier       `protobuf:"bytes,2,opt,name=build_identifier,json=buildIdentifier,proto3" json:"build_identifier,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_artifacts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{1}
}

func (x *ListArtifactsResponse) GetArtifacts() []*ArtifactSummary {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ListArtifactsResponse) GetBuildIdentifier() *BuildIdentifier {
	if x != nil {
		return x.BuildIdentifier
	}
	return nil
}

// GetArtifactRequest is used to request details of a specific artifact.
type GetArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactRequest) Reset() {
	*x = GetArtifactRequest{}
	mi := &file_artifacts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactRequest) ProtoMessage() {}

func (x *GetArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{2}
}

func (x *GetArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

// DownloadArtifactRequest is used to request the download of an artifact.
type DownloadArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactRequest) Reset() {
	*x = DownloadArtifactRequest{}
	mi := &file_artifacts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactRequest) ProtoMessage() {}

func (x *DownloadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactRequest.ProtoReflect.Descriptor instead.
func (*DownloadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

// DownloadArtifactResponse provides the download URL for a requested artifact.
type DownloadArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactResponse) Reset() {
	*x = DownloadArtifactResponse{}
	mi := &file_artifacts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactResponse) ProtoMessage() {}

func (x *DownloadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactResponse.ProtoReflect.Descriptor instead.
func (*DownloadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadArtifactResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

// DeleteArtifactRequest is used to request deletion of a specific artifact.
type DeleteArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactRequest) Reset() {
	*x = DeleteArtifactRequest{}
	mi := &file_artifacts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactRequest) ProtoMessage() {}

func (x *DeleteArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

// DeleteArtifactResponse confirms the deletion of an artifact.
type DeleteArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactResponse) Reset() {
	*x = DeleteArtifactResponse{}
	mi := &file_artifacts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactResponse) ProtoMessage() {}

func (x *DeleteArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactResponse.ProtoReflect.Descriptor instead.
func (*DeleteArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteArtifactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ArtifactSummary is used to download a specific artifact.
type ArtifactSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactSummary) Reset() {
	*x = ArtifactSummary{}
	mi := &file_artifacts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSummary) ProtoMessage() {}

func (x *ArtifactSummary) ProtoReflect() protoreflect.Message {
	mi := &file_artifacts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSummary.ProtoReflect.Descriptor instead.
func (*ArtifactSummary) Descriptor() ([]byte, []int) {
	return file_artifacts_proto_rawDescGZIP(), []int{7}
}

func (x *ArtifactSummary) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ArtifactSummary) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ArtifactSummary) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactSummary) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

var File_artifacts_proto protoreflect.FileDescriptor

const file_artifacts_proto_rawDesc = "" +
	"\n" +
	"\x0fartifacts.proto\x12\bsmidr.v1\x1a\fcommon.proto\"\\\n" +
	"\x14ListArtifactsRequest\x12D\n" +
	"\x10build_identifier\x18\x01 \x01(\v2\x19.smidr.v1.BuildIdentifierR\x0fbuildIdentifier\"\x96\x01\n" +
	"\x15ListArtifactsResponse\x127\n" +
	"\tartifacts\x18\x01 \x03(\v2\x19.smidr.v1.ArtifactSummaryR\tartifacts\x12D\n" +
	"\x10build_identifier\x18\x02 \x01(\v2\x19.smidr.v1.BuildIdentifierR\x0fbuildIdentifier\"5\n" +
	"\x12GetArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\":\n" +
	"\x17DownloadArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"=\n" +
	"\x18DownloadArtifactResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\"8\n" +
	"\x15DeleteArtifactRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\"2\n" +
	"\x16DeleteArtifactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb8\x01\n" +
	"\x0fArtifactSummary\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\fdownload_url\x18\x04 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum2\xdb\x02\n" +
	"\x0fArtifactService\x12P\n" +
	"\rListArtifacts\x12\x1e.smidr.v1.ListArtifactsRequest\x1a\x1f.smidr.v1.ListArtifactsResponse\x12F\n" +
	"\vGetArtifact\x12\x1c.smidr.v1.GetArtifactRequest\x1a\x19.smidr.v1.ArtifactSummary\x12Y\n" +
	"\x10DownloadArtifact\x12!.smidr.v1.DownloadArtifactRequest\x1a\".smidr.v1.DownloadArtifactResponse\x12S\n" +
	"\x0eDeleteArtifact\x12\x1f.smidr.v1.DeleteArtifactRequest\x1a .smidr.v1.DeleteArtifactResponseB\x99\x01\n" +
	"\fcom.smidr.v1B\x0eArtifactsProtoP\x01Z8github.com/schererja/smidr/sdks/pkg/smidr-sdk/v1;smidrv1\xa2\x02\x03SXX\xaa\x02\bSmidr.V1\xca\x02\bSmidr\\V1\xe2\x02\x14Smidr\\V1\\GPBMetadata\xea\x02\tSmidr::V1b\x06proto3"

var (
	file_artifacts_proto_rawDescOnce sync.Once
	file_artifacts_proto_rawDescData []byte
)

func file_artifacts_proto_rawDescGZIP() []byte {
	file_artifacts_proto_rawDescOnce.Do(func() {
		file_artifacts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifacts_proto_rawDesc), len(file_artifacts_proto_rawDesc)))
	})
	return file_artifacts_proto_rawDescData
}

var file_artifacts_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_artifacts_proto_goTypes = []any{
	(*ListArtifactsRequest)(nil),     // 0: smidr.v1.ListArtifactsRequest
	(*ListArtifactsResponse)(nil),    // 1: smidr.v1.ListArtifactsResponse
	(*GetArtifactRequest)(nil),       // 2: smidr.v1.GetArtifactRequest
	(*DownloadArtifactRequest)(nil),  // 3: smidr.v1.DownloadArtifactRequest
	(*DownloadArtifactResponse)(nil), // 4: smidr.v1.DownloadArtifactResponse
	(*DeleteArtifactRequest)(nil),    // 5: smidr.v1.DeleteArtifactRequest
	(*DeleteArtifactResponse)(nil),   // 6: smidr.v1.DeleteArtifactResponse
	(*ArtifactSummary)(nil),          // 7: smidr.v1.ArtifactSummary
	(*BuildIdentifier)(nil),          // 8: smidr.v1.BuildIdentifier
}
var file_artifacts_proto_depIdxs = []int32{
	8, // 0: smidr.v1.ListArtifactsRequest.build_identifier:type_name -> smidr.v1.BuildIdentifier
	7, // 1: smidr.v1.ListArtifactsResponse.artifacts:type_name -> smidr.v1.ArtifactSummary
	8, // 2: smidr.v1.ListArtifactsResponse.build_identifier:type_name -> smidr.v1.BuildIdentifier
	0, // 3: smidr.v1.ArtifactService.ListArtifacts:input_type -> smidr.v1.ListArtifactsRequest
	2, // 4: smidr.v1.ArtifactService.GetArtifact:input_type -> smidr.v1.GetArtifactRequest
	3, // 5: smidr.v1.ArtifactService.DownloadArtifact:input_type -> smidr.v1.DownloadArtifactRequest
	5, // 6: smidr.v1.ArtifactService.DeleteArtifact:input_type -> smidr.v1.DeleteArtifactRequest
	1, // 7: smidr.v1.ArtifactService.ListArtifacts:output_type -> smidr.v1.ListArtifactsResponse
	7, // 8: smidr.v1.ArtifactService.GetArtifact:output_type -> smidr.v1.ArtifactSummary
	4, // 9: smidr.v1.ArtifactService.DownloadArtifact:output_type -> smidr.v1.DownloadArtifactResponse
	6, // 10: smidr.v1.ArtifactService.DeleteArtifact:output_type -> smidr.v1.DeleteArtifactResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_artifacts_proto_init() }
func file_artifacts_proto_init() {
	if File_artifacts_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifacts_proto_rawDesc), len(file_artifacts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifacts_proto_goTypes,
		DependencyIndexes: file_artifacts_proto_depIdxs,
		MessageInfos:      file_artifacts_proto_msgTypes,
	}.Build()
	File_artifacts_proto = out.File
	file_artifacts_proto_goTypes = nil
	file_artifacts_proto_depIdxs = nil
}
