package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a new Smidr project configuration",
	Long: `Initialize a new Smidr project by generating a template configuration file (smidr.yaml) in the current directory.

If a project name is provided, it will be used in the generated config. If not, 'my-smidr-project' is used by default.

This command will not overwrite an existing smidr.yaml file.`,
	Example: `  smidr init
  smidr init myproject
  smidr init "Acme IoT Gateway"`,
	Args: cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		projectName := "my-smidr-project"
		if len(args) == 1 {
			projectName = args[0]
		}
		if err := initProject(projectName); err != nil {
			fmt.Println("Error initializing project:", err)
			return
		}
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func initProject(projectName string) error {
	configPath := "smidr.yaml"
	if _, err := os.Stat(configPath); err == nil {
		return fmt.Errorf("configuration file %s already exists", configPath)
	}

	// Create the template file
	template := generateConfigTemplate(projectName)
	if err := os.WriteFile(configPath, []byte(template), 0644); err != nil {
		return fmt.Errorf("failed to write configuration file: %w", err)
	}
	fmt.Printf("✅ Initialized Smidr project: %s\n", projectName)
	fmt.Println("📝 Edit smidr.yaml to configure your build")
	fmt.Println("🚀 Run 'smidr build' to start building")
	return nil
}

func generateConfigTemplate(projectName string) string {
	return fmt.Sprintf(`# Smidr Build Configuration
  # Generated by 'smidr init %s'

  name: %s
  description: "Custom embedded Linux image"
  yocto_series: kirkstone
  # Base system configuration
  base:
    provider: toradex
    machine: verdin-imx8mp
    distro: poky
    version: "6.0.0"



  # Layer configuration
  # Only 'git' (and optional 'branch') are needed for remote layers. All valid sublayers will be auto-discovered.
  # Use 'path' only for custom/local layers or to override auto-discovery.
  layers:
    - name: poky
      git: "https://git.yoctoproject.org/poky"
    - name: meta-freescale
      git: "https://github.com/Freescale/meta-freescale.git"
      branch: kirkstone
    - name: meta-freescale-3rdparty
      git: "https://github.com/Freescale/meta-freescale-3rdparty.git"
      branch: kirkstone
    - name: meta-openembedded
      git: "https://git.openembedded.org/meta-openembedded"
    - name: meta-toradex-bsp-common
      git: "https://git.toradex.com/meta-toradex-bsp-common.git"
    - name: meta-toradex-nxp
      git: "https://git.toradex.com/meta-toradex-nxp.git"

    # Custom/local layers (example):
    # - name: meta-mycompany
    #   path: meta-mycompany
    #   git: ../meta-mycompany
    #
    # - name: meta-myapp
    #   path: meta-myapp

  # Build configuration - use the minimal to start and always start with qemux86-64
  build:
    image: core-image-minimal
    machine: qemux86-64

    # Extra packages to include
    extra_packages:
      - python3
      - nodejs
      - vim

    # Build options
    parallel_make: 8
    bb_number_threads: 8

  # Output artifacts to extract
  artifacts:
    - "*.wic"           # Disk images
    - "*.tar.bz2"       # Root filesystem archives
    - "*-sdk-*.sh"      # SDK installers

  # Directory configuration (all default to ~/.smidr/*)
  directories:
    downloads: ~/.smidr/downloads
    layers: ~/.smidr/layers
    sstate: ~/.smidr/sstate-cache
    tmp: ~/.smidr/tmp
    build: ~/.smidr/build
    deploy: ~/.smidr/deploy
    source: ~/.smidr/sources

  # Container configuration
  container:
    # Base image for builds (using official Yocto project image)
    base_image: "crops/yocto:ubuntu-22.04-base"

    # Resource limits
    memory: "8g"
    cpu_count: 8

  # Cache configuration
  cache:
    # Shared cache locations (defaults to ~/.smidr)
    downloads: ~/.smidr/downloads
    sstate: ~/.smidr/sstate-cache

    # Cache retention (days)
    retention: 30
  `, projectName, projectName)
}
