// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: smidr.proto

package smidrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuildState represents the current state of a build
type BuildState int32

const (
	BuildState_BUILD_STATE_UNKNOWN              BuildState = 0
	BuildState_BUILD_STATE_QUEUED               BuildState = 1
	BuildState_BUILD_STATE_PREPARING            BuildState = 2
	BuildState_BUILD_STATE_BUILDING             BuildState = 3
	BuildState_BUILD_STATE_EXTRACTING_ARTIFACTS BuildState = 4
	BuildState_BUILD_STATE_COMPLETED            BuildState = 5
	BuildState_BUILD_STATE_FAILED               BuildState = 6
	BuildState_BUILD_STATE_CANCELLED            BuildState = 7
)

// Enum value maps for BuildState.
var (
	BuildState_name = map[int32]string{
		0: "BUILD_STATE_UNKNOWN",
		1: "BUILD_STATE_QUEUED",
		2: "BUILD_STATE_PREPARING",
		3: "BUILD_STATE_BUILDING",
		4: "BUILD_STATE_EXTRACTING_ARTIFACTS",
		5: "BUILD_STATE_COMPLETED",
		6: "BUILD_STATE_FAILED",
		7: "BUILD_STATE_CANCELLED",
	}
	BuildState_value = map[string]int32{
		"BUILD_STATE_UNKNOWN":              0,
		"BUILD_STATE_QUEUED":               1,
		"BUILD_STATE_PREPARING":            2,
		"BUILD_STATE_BUILDING":             3,
		"BUILD_STATE_EXTRACTING_ARTIFACTS": 4,
		"BUILD_STATE_COMPLETED":            5,
		"BUILD_STATE_FAILED":               6,
		"BUILD_STATE_CANCELLED":            7,
	}
)

func (x BuildState) Enum() *BuildState {
	p := new(BuildState)
	*p = x
	return p
}

func (x BuildState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildState) Descriptor() protoreflect.EnumDescriptor {
	return file_smidr_proto_enumTypes[0].Descriptor()
}

func (BuildState) Type() protoreflect.EnumType {
	return &file_smidr_proto_enumTypes[0]
}

func (x BuildState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildState.Descriptor instead.
func (BuildState) EnumDescriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{0}
}

// StartBuildRequest contains the configuration for starting a new build
type StartBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config file path or inline YAML content
	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Build target (e.g., "core-image-minimal")
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Force clean build
	ForceClean bool `protobuf:"varint,3,opt,name=force_clean,json=forceClean,proto3" json:"force_clean,omitempty"`
	// Force image regeneration only
	ForceImage bool `protobuf:"varint,4,opt,name=force_image,json=forceImage,proto3" json:"force_image,omitempty"`
	// Additional environment variables
	EnvVars map[string]string `protobuf:"bytes,5,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional customer/project name for build ID grouping
	Customer      string `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBuildRequest) Reset() {
	*x = StartBuildRequest{}
	mi := &file_smidr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBuildRequest) ProtoMessage() {}

func (x *StartBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBuildRequest.ProtoReflect.Descriptor instead.
func (*StartBuildRequest) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{0}
}

func (x *StartBuildRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartBuildRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *StartBuildRequest) GetForceClean() bool {
	if x != nil {
		return x.ForceClean
	}
	return false
}

func (x *StartBuildRequest) GetForceImage() bool {
	if x != nil {
		return x.ForceImage
	}
	return false
}

func (x *StartBuildRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *StartBuildRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

// BuildStatusRequest requests status for a specific build
type BuildStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStatusRequest) Reset() {
	*x = BuildStatusRequest{}
	mi := &file_smidr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStatusRequest) ProtoMessage() {}

func (x *BuildStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStatusRequest.ProtoReflect.Descriptor instead.
func (*BuildStatusRequest) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{1}
}

func (x *BuildStatusRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

// BuildStatus contains the current state of a build
type BuildStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	State         BuildState             `protobuf:"varint,3,opt,name=state,proto3,enum=smidr.v1.BuildState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`       // Unix timestamp
	CompletedAt   int64                  `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // Unix timestamp
	ConfigPath    string                 `protobuf:"bytes,8,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStatus) Reset() {
	*x = BuildStatus{}
	mi := &file_smidr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStatus) ProtoMessage() {}

func (x *BuildStatus) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStatus.ProtoReflect.Descriptor instead.
func (*BuildStatus) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{2}
}

func (x *BuildStatus) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildStatus) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *BuildStatus) GetState() BuildState {
	if x != nil {
		return x.State
	}
	return BuildState_BUILD_STATE_UNKNOWN
}

func (x *BuildStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *BuildStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BuildStatus) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *BuildStatus) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *BuildStatus) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

// StreamLogsRequest requests log streaming for a specific build
type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"` // Continue streaming new logs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_smidr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{3}
}

func (x *StreamLogsRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *StreamLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

// LogLine represents a single log line
type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in nanoseconds
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`        // "stdout" or "stderr"
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`      // Log line content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_smidr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{4}
}

func (x *LogLine) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogLine) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ListArtifactsRequest requests artifacts for a specific build
type ListArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_smidr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{5}
}

func (x *ListArtifactsRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

// ArtifactsList contains all artifacts from a build
type ArtifactsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Artifacts     []*Artifact            `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactsList) Reset() {
	*x = ArtifactsList{}
	mi := &file_smidr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactsList) ProtoMessage() {}

func (x *ArtifactsList) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactsList.ProtoReflect.Descriptor instead.
func (*ArtifactsList) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{6}
}

func (x *ArtifactsList) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *ArtifactsList) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

// Artifact represents a single build artifact
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_smidr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{7}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Artifact) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// CancelBuildRequest requests cancellation of a build
type CancelBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBuildRequest) Reset() {
	*x = CancelBuildRequest{}
	mi := &file_smidr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBuildRequest) ProtoMessage() {}

func (x *CancelBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBuildRequest.ProtoReflect.Descriptor instead.
func (*CancelBuildRequest) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{8}
}

func (x *CancelBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

// CancelResult indicates the result of a cancellation request
type CancelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResult) Reset() {
	*x = CancelResult{}
	mi := &file_smidr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResult) ProtoMessage() {}

func (x *CancelResult) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResult.ProtoReflect.Descriptor instead.
func (*CancelResult) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{9}
}

func (x *CancelResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListBuildsRequest requests a list of builds
type ListBuildsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by state (empty = all states)
	States []BuildState `protobuf:"varint,1,rep,packed,name=states,proto3,enum=smidr.v1.BuildState" json:"states,omitempty"`
	// Maximum number of results
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsRequest) Reset() {
	*x = ListBuildsRequest{}
	mi := &file_smidr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsRequest) ProtoMessage() {}

func (x *ListBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsRequest.ProtoReflect.Descriptor instead.
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{10}
}

func (x *ListBuildsRequest) GetStates() []BuildState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ListBuildsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// BuildsList contains a list of builds
type BuildsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*BuildStatus         `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildsList) Reset() {
	*x = BuildsList{}
	mi := &file_smidr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildsList) ProtoMessage() {}

func (x *BuildsList) ProtoReflect() protoreflect.Message {
	mi := &file_smidr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildsList.ProtoReflect.Descriptor instead.
func (*BuildsList) Descriptor() ([]byte, []int) {
	return file_smidr_proto_rawDescGZIP(), []int{11}
}

func (x *BuildsList) GetBuilds() []*BuildStatus {
	if x != nil {
		return x.Builds
	}
	return nil
}

var File_smidr_proto protoreflect.FileDescriptor

const file_smidr_proto_rawDesc = "" +
	"\n" +
	"\vsmidr.proto\x12\bsmidr.v1\"\xa2\x02\n" +
	"\x11StartBuildRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1f\n" +
	"\vforce_clean\x18\x03 \x01(\bR\n" +
	"forceClean\x12\x1f\n" +
	"\vforce_image\x18\x04 \x01(\bR\n" +
	"forceImage\x12C\n" +
	"\benv_vars\x18\x05 \x03(\v2(.smidr.v1.StartBuildRequest.EnvVarsEntryR\aenvVars\x12\x1a\n" +
	"\bcustomer\x18\x06 \x01(\tR\bcustomer\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x12BuildStatusRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"\x91\x02\n" +
	"\vBuildStatus\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.smidr.v1.BuildStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\a \x01(\x03R\vcompletedAt\x12\x1f\n" +
	"\vconfig_path\x18\b \x01(\tR\n" +
	"configPath\"F\n" +
	"\x11StreamLogsRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"Y\n" +
	"\aLogLine\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"1\n" +
	"\x14ListArtifactsRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"\\\n" +
	"\rArtifactsList\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x120\n" +
	"\tartifacts\x18\x02 \x03(\v2\x12.smidr.v1.ArtifactR\tartifacts\"b\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"/\n" +
	"\x12CancelBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"B\n" +
	"\fCancelResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x11ListBuildsRequest\x12,\n" +
	"\x06states\x18\x01 \x03(\x0e2\x14.smidr.v1.BuildStateR\x06states\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\";\n" +
	"\n" +
	"BuildsList\x12-\n" +
	"\x06builds\x18\x01 \x03(\v2\x15.smidr.v1.BuildStatusR\x06builds*\xe6\x01\n" +
	"\n" +
	"BuildState\x12\x17\n" +
	"\x13BUILD_STATE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12BUILD_STATE_QUEUED\x10\x01\x12\x19\n" +
	"\x15BUILD_STATE_PREPARING\x10\x02\x12\x18\n" +
	"\x14BUILD_STATE_BUILDING\x10\x03\x12$\n" +
	" BUILD_STATE_EXTRACTING_ARTIFACTS\x10\x04\x12\x19\n" +
	"\x15BUILD_STATE_COMPLETED\x10\x05\x12\x16\n" +
	"\x12BUILD_STATE_FAILED\x10\x06\x12\x19\n" +
	"\x15BUILD_STATE_CANCELLED\x10\a2\xa0\x03\n" +
	"\x05Smidr\x12@\n" +
	"\n" +
	"StartBuild\x12\x1b.smidr.v1.StartBuildRequest\x1a\x15.smidr.v1.BuildStatus\x12E\n" +
	"\x0eGetBuildStatus\x12\x1c.smidr.v1.BuildStatusRequest\x1a\x15.smidr.v1.BuildStatus\x12>\n" +
	"\n" +
	"StreamLogs\x12\x1b.smidr.v1.StreamLogsRequest\x1a\x11.smidr.v1.LogLine0\x01\x12H\n" +
	"\rListArtifacts\x12\x1e.smidr.v1.ListArtifactsRequest\x1a\x17.smidr.v1.ArtifactsList\x12C\n" +
	"\vCancelBuild\x12\x1c.smidr.v1.CancelBuildRequest\x1a\x16.smidr.v1.CancelResult\x12?\n" +
	"\n" +
	"ListBuilds\x12\x1b.smidr.v1.ListBuildsRequest\x1a\x14.smidr.v1.BuildsListB;Z9github.com/schererja/smidr-protos/gen/go/smidr/v1;smidrv1b\x06proto3"

var (
	file_smidr_proto_rawDescOnce sync.Once
	file_smidr_proto_rawDescData []byte
)

func file_smidr_proto_rawDescGZIP() []byte {
	file_smidr_proto_rawDescOnce.Do(func() {
		file_smidr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smidr_proto_rawDesc), len(file_smidr_proto_rawDesc)))
	})
	return file_smidr_proto_rawDescData
}

var file_smidr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_smidr_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_smidr_proto_goTypes = []any{
	(BuildState)(0),              // 0: smidr.v1.BuildState
	(*StartBuildRequest)(nil),    // 1: smidr.v1.StartBuildRequest
	(*BuildStatusRequest)(nil),   // 2: smidr.v1.BuildStatusRequest
	(*BuildStatus)(nil),          // 3: smidr.v1.BuildStatus
	(*StreamLogsRequest)(nil),    // 4: smidr.v1.StreamLogsRequest
	(*LogLine)(nil),              // 5: smidr.v1.LogLine
	(*ListArtifactsRequest)(nil), // 6: smidr.v1.ListArtifactsRequest
	(*ArtifactsList)(nil),        // 7: smidr.v1.ArtifactsList
	(*Artifact)(nil),             // 8: smidr.v1.Artifact
	(*CancelBuildRequest)(nil),   // 9: smidr.v1.CancelBuildRequest
	(*CancelResult)(nil),         // 10: smidr.v1.CancelResult
	(*ListBuildsRequest)(nil),    // 11: smidr.v1.ListBuildsRequest
	(*BuildsList)(nil),           // 12: smidr.v1.BuildsList
	nil,                          // 13: smidr.v1.StartBuildRequest.EnvVarsEntry
}
var file_smidr_proto_depIdxs = []int32{
	13, // 0: smidr.v1.StartBuildRequest.env_vars:type_name -> smidr.v1.StartBuildRequest.EnvVarsEntry
	0,  // 1: smidr.v1.BuildStatus.state:type_name -> smidr.v1.BuildState
	8,  // 2: smidr.v1.ArtifactsList.artifacts:type_name -> smidr.v1.Artifact
	0,  // 3: smidr.v1.ListBuildsRequest.states:type_name -> smidr.v1.BuildState
	3,  // 4: smidr.v1.BuildsList.builds:type_name -> smidr.v1.BuildStatus
	1,  // 5: smidr.v1.Smidr.StartBuild:input_type -> smidr.v1.StartBuildRequest
	2,  // 6: smidr.v1.Smidr.GetBuildStatus:input_type -> smidr.v1.BuildStatusRequest
	4,  // 7: smidr.v1.Smidr.StreamLogs:input_type -> smidr.v1.StreamLogsRequest
	6,  // 8: smidr.v1.Smidr.ListArtifacts:input_type -> smidr.v1.ListArtifactsRequest
	9,  // 9: smidr.v1.Smidr.CancelBuild:input_type -> smidr.v1.CancelBuildRequest
	11, // 10: smidr.v1.Smidr.ListBuilds:input_type -> smidr.v1.ListBuildsRequest
	3,  // 11: smidr.v1.Smidr.StartBuild:output_type -> smidr.v1.BuildStatus
	3,  // 12: smidr.v1.Smidr.GetBuildStatus:output_type -> smidr.v1.BuildStatus
	5,  // 13: smidr.v1.Smidr.StreamLogs:output_type -> smidr.v1.LogLine
	7,  // 14: smidr.v1.Smidr.ListArtifacts:output_type -> smidr.v1.ArtifactsList
	10, // 15: smidr.v1.Smidr.CancelBuild:output_type -> smidr.v1.CancelResult
	12, // 16: smidr.v1.Smidr.ListBuilds:output_type -> smidr.v1.BuildsList
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_smidr_proto_init() }
func file_smidr_proto_init() {
	if File_smidr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smidr_proto_rawDesc), len(file_smidr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smidr_proto_goTypes,
		DependencyIndexes: file_smidr_proto_depIdxs,
		EnumInfos:         file_smidr_proto_enumTypes,
		MessageInfos:      file_smidr_proto_msgTypes,
	}.Build()
	File_smidr_proto = out.File
	file_smidr_proto_goTypes = nil
	file_smidr_proto_depIdxs = nil
}
