// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file artifacts.proto (package smidr.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { BuildIdentifier } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file artifacts.proto.
 */
export const file_artifacts: GenFile = /*@__PURE__*/
  fileDesc("Cg9hcnRpZmFjdHMucHJvdG8SCHNtaWRyLnYxIksKFExpc3RBcnRpZmFjdHNSZXF1ZXN0EjMKEGJ1aWxkX2lkZW50aWZpZXIYASABKAsyGS5zbWlkci52MS5CdWlsZElkZW50aWZpZXIiRQoVTGlzdEFydGlmYWN0c1Jlc3BvbnNlEiwKCWFydGlmYWN0cxgBIAMoCzIZLnNtaWRyLnYxLkFydGlmYWN0U3VtbWFyeSIpChJHZXRBcnRpZmFjdFJlcXVlc3QSEwoLYXJ0aWZhY3RfaWQYASABKAkiLgoXRG93bmxvYWRBcnRpZmFjdFJlcXVlc3QSEwoLYXJ0aWZhY3RfaWQYASABKAkiMAoYRG93bmxvYWRBcnRpZmFjdFJlc3BvbnNlEhQKDGRvd25sb2FkX3VybBgBIAEoCSIsChVEZWxldGVBcnRpZmFjdFJlcXVlc3QSEwoLYXJ0aWZhY3RfaWQYASABKAkiKQoWRGVsZXRlQXJ0aWZhY3RSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIn4KD0FydGlmYWN0U3VtbWFyeRITCgthcnRpZmFjdF9pZBgBIAEoCRIMCgRuYW1lGAIgASgJEgwKBHR5cGUYAyABKAkSFAoMZG93bmxvYWRfdXJsGAQgASgJEhIKCnNpemVfYnl0ZXMYBSABKAMSEAoIY2hlY2tzdW0YBiABKAky2wIKD0FydGlmYWN0U2VydmljZRJQCg1MaXN0QXJ0aWZhY3RzEh4uc21pZHIudjEuTGlzdEFydGlmYWN0c1JlcXVlc3QaHy5zbWlkci52MS5MaXN0QXJ0aWZhY3RzUmVzcG9uc2USRgoLR2V0QXJ0aWZhY3QSHC5zbWlkci52MS5HZXRBcnRpZmFjdFJlcXVlc3QaGS5zbWlkci52MS5BcnRpZmFjdFN1bW1hcnkSWQoQRG93bmxvYWRBcnRpZmFjdBIhLnNtaWRyLnYxLkRvd25sb2FkQXJ0aWZhY3RSZXF1ZXN0GiIuc21pZHIudjEuRG93bmxvYWRBcnRpZmFjdFJlc3BvbnNlElMKDkRlbGV0ZUFydGlmYWN0Eh8uc21pZHIudjEuRGVsZXRlQXJ0aWZhY3RSZXF1ZXN0GiAuc21pZHIudjEuRGVsZXRlQXJ0aWZhY3RSZXNwb25zZUKaAQoMY29tLnNtaWRyLnYxQg5BcnRpZmFjdHNQcm90b1ABWjlnaXRodWIuY29tL3NjaGVyZXJqYS9zbWlkci1wcm90b3MvZ2VuL2dvL3NtaWRyL3YxO3NtaWRydjGiAgNTWFiqAghTbWlkci5WMcoCCFNtaWRyXFYx4gIUU21pZHJcVjFcR1BCTWV0YWRhdGHqAglTbWlkcjo6VjFiBnByb3RvMw", [file_common]);

/**
 * ListArtifactsRequest is used to request a list of artifacts for an build.
 *
 * @generated from message smidr.v1.ListArtifactsRequest
 */
export type ListArtifactsRequest = Message<"smidr.v1.ListArtifactsRequest"> & {
  /**
   * @generated from field: smidr.v1.BuildIdentifier build_identifier = 1;
   */
  buildIdentifier?: BuildIdentifier;
};

/**
 * Describes the message smidr.v1.ListArtifactsRequest.
 * Use `create(ListArtifactsRequestSchema)` to create a new message.
 */
export const ListArtifactsRequestSchema: GenMessage<ListArtifactsRequest> = /*@__PURE__*/
  messageDesc(file_artifacts, 0);

/**
 * ListArtifactsResponse contains a list of artifacts associated with a build.
 *
 * @generated from message smidr.v1.ListArtifactsResponse
 */
export type ListArtifactsResponse = Message<"smidr.v1.ListArtifactsResponse"> & {
  /**
   * @generated from field: repeated smidr.v1.ArtifactSummary artifacts = 1;
   */
  artifacts: ArtifactSummary[];
};

/**
 * Describes the message smidr.v1.ListArtifactsResponse.
 * Use `create(ListArtifactsResponseSchema)` to create a new message.
 */
export const ListArtifactsResponseSchema: GenMessage<ListArtifactsResponse> = /*@__PURE__*/
  messageDesc(file_artifacts, 1);

/**
 * GetArtifactRequest is used to request details of a specific artifact.
 *
 * @generated from message smidr.v1.GetArtifactRequest
 */
export type GetArtifactRequest = Message<"smidr.v1.GetArtifactRequest"> & {
  /**
   * @generated from field: string artifact_id = 1;
   */
  artifactId: string;
};

/**
 * Describes the message smidr.v1.GetArtifactRequest.
 * Use `create(GetArtifactRequestSchema)` to create a new message.
 */
export const GetArtifactRequestSchema: GenMessage<GetArtifactRequest> = /*@__PURE__*/
  messageDesc(file_artifacts, 2);

/**
 * DownloadArtifactRequest is used to request the download of an artifact.
 *
 * @generated from message smidr.v1.DownloadArtifactRequest
 */
export type DownloadArtifactRequest = Message<"smidr.v1.DownloadArtifactRequest"> & {
  /**
   * @generated from field: string artifact_id = 1;
   */
  artifactId: string;
};

/**
 * Describes the message smidr.v1.DownloadArtifactRequest.
 * Use `create(DownloadArtifactRequestSchema)` to create a new message.
 */
export const DownloadArtifactRequestSchema: GenMessage<DownloadArtifactRequest> = /*@__PURE__*/
  messageDesc(file_artifacts, 3);

/**
 * DownloadArtifactResponse provides the download URL for a requested artifact.
 *
 * @generated from message smidr.v1.DownloadArtifactResponse
 */
export type DownloadArtifactResponse = Message<"smidr.v1.DownloadArtifactResponse"> & {
  /**
   * @generated from field: string download_url = 1;
   */
  downloadUrl: string;
};

/**
 * Describes the message smidr.v1.DownloadArtifactResponse.
 * Use `create(DownloadArtifactResponseSchema)` to create a new message.
 */
export const DownloadArtifactResponseSchema: GenMessage<DownloadArtifactResponse> = /*@__PURE__*/
  messageDesc(file_artifacts, 4);

/**
 * DeleteArtifactRequest is used to request deletion of a specific artifact.
 *
 * @generated from message smidr.v1.DeleteArtifactRequest
 */
export type DeleteArtifactRequest = Message<"smidr.v1.DeleteArtifactRequest"> & {
  /**
   * @generated from field: string artifact_id = 1;
   */
  artifactId: string;
};

/**
 * Describes the message smidr.v1.DeleteArtifactRequest.
 * Use `create(DeleteArtifactRequestSchema)` to create a new message.
 */
export const DeleteArtifactRequestSchema: GenMessage<DeleteArtifactRequest> = /*@__PURE__*/
  messageDesc(file_artifacts, 5);

/**
 * DeleteArtifactResponse confirms the deletion of an artifact.
 *
 * @generated from message smidr.v1.DeleteArtifactResponse
 */
export type DeleteArtifactResponse = Message<"smidr.v1.DeleteArtifactResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message smidr.v1.DeleteArtifactResponse.
 * Use `create(DeleteArtifactResponseSchema)` to create a new message.
 */
export const DeleteArtifactResponseSchema: GenMessage<DeleteArtifactResponse> = /*@__PURE__*/
  messageDesc(file_artifacts, 6);

/**
 * ArtifactSummary is used to download a specific artifact.
 *
 * @generated from message smidr.v1.ArtifactSummary
 */
export type ArtifactSummary = Message<"smidr.v1.ArtifactSummary"> & {
  /**
   * @generated from field: string artifact_id = 1;
   */
  artifactId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * @generated from field: string download_url = 4;
   */
  downloadUrl: string;

  /**
   * @generated from field: int64 size_bytes = 5;
   */
  sizeBytes: bigint;

  /**
   * @generated from field: string checksum = 6;
   */
  checksum: string;
};

/**
 * Describes the message smidr.v1.ArtifactSummary.
 * Use `create(ArtifactSummarySchema)` to create a new message.
 */
export const ArtifactSummarySchema: GenMessage<ArtifactSummary> = /*@__PURE__*/
  messageDesc(file_artifacts, 7);

/**
 * @generated from service smidr.v1.ArtifactService
 */
export const ArtifactService: GenService<{
  /**
   * @generated from rpc smidr.v1.ArtifactService.ListArtifacts
   */
  listArtifacts: {
    methodKind: "unary";
    input: typeof ListArtifactsRequestSchema;
    output: typeof ListArtifactsResponseSchema;
  },
  /**
   * @generated from rpc smidr.v1.ArtifactService.GetArtifact
   */
  getArtifact: {
    methodKind: "unary";
    input: typeof GetArtifactRequestSchema;
    output: typeof ArtifactSummarySchema;
  },
  /**
   * @generated from rpc smidr.v1.ArtifactService.DownloadArtifact
   */
  downloadArtifact: {
    methodKind: "unary";
    input: typeof DownloadArtifactRequestSchema;
    output: typeof DownloadArtifactResponseSchema;
  },
  /**
   * @generated from rpc smidr.v1.ArtifactService.DeleteArtifact
   */
  deleteArtifact: {
    methodKind: "unary";
    input: typeof DeleteArtifactRequestSchema;
    output: typeof DeleteArtifactResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_artifacts, 0);

