// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file artifacts.proto (package smidr.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { BuildIdentifier } from "./common_pb";
import { file_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file artifacts.proto.
 */
export const file_artifacts: GenFile = /*@__PURE__*/
  fileDesc("Cg9hcnRpZmFjdHMucHJvdG8SCHNtaWRyLnYxIksKFExpc3RBcnRpZmFjdHNSZXF1ZXN0EjMKEGJ1aWxkX2lkZW50aWZpZXIYASABKAsyGS5zbWlkci52MS5CdWlsZElkZW50aWZpZXIiegoVTGlzdEFydGlmYWN0c1Jlc3BvbnNlEiwKCWFydGlmYWN0cxgBIAMoCzIZLnNtaWRyLnYxLkFydGlmYWN0U3VtbWFyeRIzChBidWlsZF9pZGVudGlmaWVyGAIgASgLMhkuc21pZHIudjEuQnVpbGRJZGVudGlmaWVyIikKEkdldEFydGlmYWN0UmVxdWVzdBITCgthcnRpZmFjdF9pZBgBIAEoCSIuChdEb3dubG9hZEFydGlmYWN0UmVxdWVzdBITCgthcnRpZmFjdF9pZBgBIAEoCSIwChhEb3dubG9hZEFydGlmYWN0UmVzcG9uc2USFAoMZG93bmxvYWRfdXJsGAEgASgJIiwKFURlbGV0ZUFydGlmYWN0UmVxdWVzdBITCgthcnRpZmFjdF9pZBgBIAEoCSIpChZEZWxldGVBcnRpZmFjdFJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgifgoPQXJ0aWZhY3RTdW1tYXJ5EhMKC2FydGlmYWN0X2lkGAEgASgJEgwKBG5hbWUYAiABKAkSDAoEdHlwZRgDIAEoCRIUCgxkb3dubG9hZF91cmwYBCABKAkSEgoKc2l6ZV9ieXRlcxgFIAEoAxIQCghjaGVja3N1bRgGIAEoCTLbAgoPQXJ0aWZhY3RTZXJ2aWNlElAKDUxpc3RBcnRpZmFjdHMSHi5zbWlkci52MS5MaXN0QXJ0aWZhY3RzUmVxdWVzdBofLnNtaWRyLnYxLkxpc3RBcnRpZmFjdHNSZXNwb25zZRJGCgtHZXRBcnRpZmFjdBIcLnNtaWRyLnYxLkdldEFydGlmYWN0UmVxdWVzdBoZLnNtaWRyLnYxLkFydGlmYWN0U3VtbWFyeRJZChBEb3dubG9hZEFydGlmYWN0EiEuc21pZHIudjEuRG93bmxvYWRBcnRpZmFjdFJlcXVlc3QaIi5zbWlkci52MS5Eb3dubG9hZEFydGlmYWN0UmVzcG9uc2USUwoORGVsZXRlQXJ0aWZhY3QSHy5zbWlkci52MS5EZWxldGVBcnRpZmFjdFJlcXVlc3QaIC5zbWlkci52MS5EZWxldGVBcnRpZmFjdFJlc3BvbnNlQpEBCgxjb20uc21pZHIudjFCDkFydGlmYWN0c1Byb3RvUAFaMGdpdGh1Yi5jb20vc2NoZXJlcmphL3NtaWRyL3BrZy9zbWlkci1zZGs7c21pZHJ2MaICA1NYWKoCCFNtaWRyLlYxygIIU21pZHJcVjHiAhRTbWlkclxWMVxHUEJNZXRhZGF0YeoCCVNtaWRyOjpWMWIGcHJvdG8z", [file_common]);

/**
 * ListArtifactsRequest is used to request a list of artifacts for an build.
 *
 * @generated from message smidr.v1.ListArtifactsRequest
 */
export type ListArtifactsRequest = Message<"smidr.v1.ListArtifactsRequest"> & {
  /**
   * @generated from field: smidr.v1.BuildIdentifier build_identifier = 1;
   */
  buildIdentifier?: BuildIdentifier;
};

/**
 * Describes the message smidr.v1.ListArtifactsRequest.
 * Use `create(ListArtifactsRequestSchema)` to create a new message.
 */
export const ListArtifactsRequestSchema: GenMessage<ListArtifactsRequest> = /*@__PURE__*/
  messageDesc(file_artifacts, 0);

/**
 * ListArtifactsResponse contains a list of artifacts associated with a build.
 *
 * @generated from message smidr.v1.ListArtifactsResponse
 */
export type ListArtifactsResponse = Message<"smidr.v1.ListArtifactsResponse"> & {
  /**
   * @generated from field: repeated smidr.v1.ArtifactSummary artifacts = 1;
   */
  artifacts: ArtifactSummary[];

  /**
   * @generated from field: smidr.v1.BuildIdentifier build_identifier = 2;
   */
  buildIdentifier?: BuildIdentifier;
};

/**
 * Describes the message smidr.v1.ListArtifactsResponse.
 * Use `create(ListArtifactsResponseSchema)` to create a new message.
 */
export const ListArtifactsResponseSchema: GenMessage<ListArtifactsResponse> = /*@__PURE__*/
  messageDesc(file_artifacts, 1);

/**
 * GetArtifactRequest is used to request details of a specific artifact.
 *
 * @generated from message smidr.v1.GetArtifactRequest
 */
export type GetArtifactRequest = Message<"smidr.v1.GetArtifactRequest"> & {
  /**
   * @generated from field: string artifact_id = 1;
   */
  artifactId: string;
};

/**
 * Describes the message smidr.v1.GetArtifactRequest.
 * Use `create(GetArtifactRequestSchema)` to create a new message.
 */
export const GetArtifactRequestSchema: GenMessage<GetArtifactRequest> = /*@__PURE__*/
  messageDesc(file_artifacts, 2);

/**
 * DownloadArtifactRequest is used to request the download of an artifact.
 *
 * @generated from message smidr.v1.DownloadArtifactRequest
 */
export type DownloadArtifactRequest = Message<"smidr.v1.DownloadArtifactRequest"> & {
  /**
   * @generated from field: string artifact_id = 1;
   */
  artifactId: string;
};

/**
 * Describes the message smidr.v1.DownloadArtifactRequest.
 * Use `create(DownloadArtifactRequestSchema)` to create a new message.
 */
export const DownloadArtifactRequestSchema: GenMessage<DownloadArtifactRequest> = /*@__PURE__*/
  messageDesc(file_artifacts, 3);

/**
 * DownloadArtifactResponse provides the download URL for a requested artifact.
 *
 * @generated from message smidr.v1.DownloadArtifactResponse
 */
export type DownloadArtifactResponse = Message<"smidr.v1.DownloadArtifactResponse"> & {
  /**
   * @generated from field: string download_url = 1;
   */
  downloadUrl: string;
};

/**
 * Describes the message smidr.v1.DownloadArtifactResponse.
 * Use `create(DownloadArtifactResponseSchema)` to create a new message.
 */
export const DownloadArtifactResponseSchema: GenMessage<DownloadArtifactResponse> = /*@__PURE__*/
  messageDesc(file_artifacts, 4);

/**
 * DeleteArtifactRequest is used to request deletion of a specific artifact.
 *
 * @generated from message smidr.v1.DeleteArtifactRequest
 */
export type DeleteArtifactRequest = Message<"smidr.v1.DeleteArtifactRequest"> & {
  /**
   * @generated from field: string artifact_id = 1;
   */
  artifactId: string;
};

/**
 * Describes the message smidr.v1.DeleteArtifactRequest.
 * Use `create(DeleteArtifactRequestSchema)` to create a new message.
 */
export const DeleteArtifactRequestSchema: GenMessage<DeleteArtifactRequest> = /*@__PURE__*/
  messageDesc(file_artifacts, 5);

/**
 * DeleteArtifactResponse confirms the deletion of an artifact.
 *
 * @generated from message smidr.v1.DeleteArtifactResponse
 */
export type DeleteArtifactResponse = Message<"smidr.v1.DeleteArtifactResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message smidr.v1.DeleteArtifactResponse.
 * Use `create(DeleteArtifactResponseSchema)` to create a new message.
 */
export const DeleteArtifactResponseSchema: GenMessage<DeleteArtifactResponse> = /*@__PURE__*/
  messageDesc(file_artifacts, 6);

/**
 * ArtifactSummary is used to download a specific artifact.
 *
 * @generated from message smidr.v1.ArtifactSummary
 */
export type ArtifactSummary = Message<"smidr.v1.ArtifactSummary"> & {
  /**
   * @generated from field: string artifact_id = 1;
   */
  artifactId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string type = 3;
   */
  type: string;

  /**
   * @generated from field: string download_url = 4;
   */
  downloadUrl: string;

  /**
   * @generated from field: int64 size_bytes = 5;
   */
  sizeBytes: bigint;

  /**
   * @generated from field: string checksum = 6;
   */
  checksum: string;
};

/**
 * Describes the message smidr.v1.ArtifactSummary.
 * Use `create(ArtifactSummarySchema)` to create a new message.
 */
export const ArtifactSummarySchema: GenMessage<ArtifactSummary> = /*@__PURE__*/
  messageDesc(file_artifacts, 7);

/**
 * @generated from service smidr.v1.ArtifactService
 */
export const ArtifactService: GenService<{
  /**
   * @generated from rpc smidr.v1.ArtifactService.ListArtifacts
   */
  listArtifacts: {
    methodKind: "unary";
    input: typeof ListArtifactsRequestSchema;
    output: typeof ListArtifactsResponseSchema;
  },
  /**
   * @generated from rpc smidr.v1.ArtifactService.GetArtifact
   */
  getArtifact: {
    methodKind: "unary";
    input: typeof GetArtifactRequestSchema;
    output: typeof ArtifactSummarySchema;
  },
  /**
   * @generated from rpc smidr.v1.ArtifactService.DownloadArtifact
   */
  downloadArtifact: {
    methodKind: "unary";
    input: typeof DownloadArtifactRequestSchema;
    output: typeof DownloadArtifactResponseSchema;
  },
  /**
   * @generated from rpc smidr.v1.ArtifactService.DeleteArtifact
   */
  deleteArtifact: {
    methodKind: "unary";
    input: typeof DeleteArtifactRequestSchema;
    output: typeof DeleteArtifactResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_artifacts, 0);

