// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file smidr_service.proto (package smidr.v1, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_builds } from "./builds_pb";
import { file_artifacts } from "./artifacts_pb";
import { file_logs } from "./logs_pb";

/**
 * Describes the file smidr_service.proto.
 */
export const file_smidr_service: GenFile = /*@__PURE__*/
  fileDesc("ChNzbWlkcl9zZXJ2aWNlLnByb3RvEghzbWlkci52MUKXAQoMY29tLnNtaWRyLnYxQhFTbWlkclNlcnZpY2VQcm90b1ABWjNnaXRodWIuY29tL3NjaGVyZXJqYS9zbWlkci9zZGtzL2dvL3NtaWRyL3YxO3NtaWRydjGiAgNTWFiqAghTbWlkci5WMcoCCFNtaWRyXFYx4gIUU21pZHJcVjFcR1BCTWV0YWRhdGHqAglTbWlkcjo6VjFiBnByb3RvMw", [file_builds, file_artifacts, file_logs]);

