// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: builds.proto

package smidrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StartBuildRequest is used to initiate a new build, specifying configuration.
type StartBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Build configuration in YAML format or path to config file.
	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Build target (e.g., core-image-minimal).
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Force a clean rebuild
	ForceClean bool `protobuf:"varint,3,opt,name=force_clean,json=forceClean,proto3" json:"force_clean,omitempty"`
	// Force image rebuild only
	ForceImageRebuild bool `protobuf:"varint,4,opt,name=force_image_rebuild,json=forceImageRebuild,proto3" json:"force_image_rebuild,omitempty"`
	// Additional Environmental Variables
	EnvironmentVariables map[string]string `protobuf:"bytes,5,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional customer identifier for customer-specific builds
	Customer      string `protobuf:"bytes,6,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBuildRequest) Reset() {
	*x = StartBuildRequest{}
	mi := &file_builds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBuildRequest) ProtoMessage() {}

func (x *StartBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBuildRequest.ProtoReflect.Descriptor instead.
func (*StartBuildRequest) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{0}
}

func (x *StartBuildRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *StartBuildRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *StartBuildRequest) GetForceClean() bool {
	if x != nil {
		return x.ForceClean
	}
	return false
}

func (x *StartBuildRequest) GetForceImageRebuild() bool {
	if x != nil {
		return x.ForceImageRebuild
	}
	return false
}

func (x *StartBuildRequest) GetEnvironmentVariables() map[string]string {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

func (x *StartBuildRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

// BuildStatusResponse provides the current status of a build.
type BuildStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuildIdentifier *BuildIdentifier       `protobuf:"bytes,1,opt,name=build_identifier,json=buildIdentifier,proto3" json:"build_identifier,omitempty"`
	Target          string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	State           BuildState             `protobuf:"varint,3,opt,name=state,proto3,enum=smidr.v1.BuildState" json:"state,omitempty"`
	ExitCode        int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamps      *TimeStampRange        `protobuf:"bytes,6,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	ConfigPath      string                 `protobuf:"bytes,7,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	Customer        string                 `protobuf:"bytes,8,opt,name=customer,proto3" json:"customer,omitempty"`
	Deleted         bool                   `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuildStatusResponse) Reset() {
	*x = BuildStatusResponse{}
	mi := &file_builds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStatusResponse) ProtoMessage() {}

func (x *BuildStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStatusResponse.ProtoReflect.Descriptor instead.
func (*BuildStatusResponse) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{1}
}

func (x *BuildStatusResponse) GetBuildIdentifier() *BuildIdentifier {
	if x != nil {
		return x.BuildIdentifier
	}
	return nil
}

func (x *BuildStatusResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *BuildStatusResponse) GetState() BuildState {
	if x != nil {
		return x.State
	}
	return BuildState_BUILD_STATE_UNSPECIFIED
}

func (x *BuildStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *BuildStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BuildStatusResponse) GetTimestamps() *TimeStampRange {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *BuildStatusResponse) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *BuildStatusResponse) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *BuildStatusResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// BuildStatusRequest is used to query the status of a specific build.
type BuildStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuildIdentifier *BuildIdentifier       `protobuf:"bytes,1,opt,name=build_identifier,json=buildIdentifier,proto3" json:"build_identifier,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuildStatusRequest) Reset() {
	*x = BuildStatusRequest{}
	mi := &file_builds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStatusRequest) ProtoMessage() {}

func (x *BuildStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStatusRequest.ProtoReflect.Descriptor instead.
func (*BuildStatusRequest) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{2}
}

func (x *BuildStatusRequest) GetBuildIdentifier() *BuildIdentifier {
	if x != nil {
		return x.BuildIdentifier
	}
	return nil
}

// BuildDetailsRequest is used to request detailed information about a build.
type BuildDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuildIdentifier *BuildIdentifier       `protobuf:"bytes,1,opt,name=build_identifier,json=buildIdentifier,proto3" json:"build_identifier,omitempty"`
	Customer        string                 `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	ProjectName     string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	TargetImage     string                 `protobuf:"bytes,4,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	Machine         string                 `protobuf:"bytes,5,opt,name=machine,proto3" json:"machine,omitempty"`
	BuildState      BuildState             `protobuf:"varint,6,opt,name=build_state,json=buildState,proto3,enum=smidr.v1.BuildState" json:"build_state,omitempty"`
	ExitCode        int32                  `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Directories used
	BuildDirectory    string `protobuf:"bytes,8,opt,name=build_directory,json=buildDirectory,proto3" json:"build_directory,omitempty"`
	DownloadDirectory string `protobuf:"bytes,9,opt,name=download_directory,json=downloadDirectory,proto3" json:"download_directory,omitempty"`
	LogFilePlain      string `protobuf:"bytes,10,opt,name=log_file_plain,json=logFilePlain,proto3" json:"log_file_plain,omitempty"`
	LogFileJsonl      string `protobuf:"bytes,11,opt,name=log_file_jsonl,json=logFileJsonl,proto3" json:"log_file_jsonl,omitempty"`
	// Metadata
	ConfigFile     string `protobuf:"bytes,12,opt,name=config_file,json=configFile,proto3" json:"config_file,omitempty"`
	ConfigSnapshot string `protobuf:"bytes,13,opt,name=config_snapshot,json=configSnapshot,proto3" json:"config_snapshot,omitempty"`
	User           string `protobuf:"bytes,14,opt,name=user,proto3" json:"user,omitempty"`
	Host           string `protobuf:"bytes,15,opt,name=host,proto3" json:"host,omitempty"`
	// Timestamps
	CreatedAt       int64           `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Timestamps      *TimeStampRange `protobuf:"bytes,17,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	DurationSeconds int32           `protobuf:"varint,18,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// Soft Delete Flag
	Deleted   bool  `protobuf:"varint,19,opt,name=deleted,proto3" json:"deleted,omitempty"`
	DeletedAt int64 `protobuf:"varint,20,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// Error tracking
	ErrorMessage string `protobuf:"bytes,21,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Artifacts summary
	ArtifactCount          int32 `protobuf:"varint,22,opt,name=artifact_count,json=artifactCount,proto3" json:"artifact_count,omitempty"`
	TotalArtifactSizeBytes int64 `protobuf:"varint,23,opt,name=total_artifact_size_bytes,json=totalArtifactSizeBytes,proto3" json:"total_artifact_size_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BuildDetails) Reset() {
	*x = BuildDetails{}
	mi := &file_builds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDetails) ProtoMessage() {}

func (x *BuildDetails) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDetails.ProtoReflect.Descriptor instead.
func (*BuildDetails) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{3}
}

func (x *BuildDetails) GetBuildIdentifier() *BuildIdentifier {
	if x != nil {
		return x.BuildIdentifier
	}
	return nil
}

func (x *BuildDetails) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *BuildDetails) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *BuildDetails) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

func (x *BuildDetails) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *BuildDetails) GetBuildState() BuildState {
	if x != nil {
		return x.BuildState
	}
	return BuildState_BUILD_STATE_UNSPECIFIED
}

func (x *BuildDetails) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *BuildDetails) GetBuildDirectory() string {
	if x != nil {
		return x.BuildDirectory
	}
	return ""
}

func (x *BuildDetails) GetDownloadDirectory() string {
	if x != nil {
		return x.DownloadDirectory
	}
	return ""
}

func (x *BuildDetails) GetLogFilePlain() string {
	if x != nil {
		return x.LogFilePlain
	}
	return ""
}

func (x *BuildDetails) GetLogFileJsonl() string {
	if x != nil {
		return x.LogFileJsonl
	}
	return ""
}

func (x *BuildDetails) GetConfigFile() string {
	if x != nil {
		return x.ConfigFile
	}
	return ""
}

func (x *BuildDetails) GetConfigSnapshot() string {
	if x != nil {
		return x.ConfigSnapshot
	}
	return ""
}

func (x *BuildDetails) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BuildDetails) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BuildDetails) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BuildDetails) GetTimestamps() *TimeStampRange {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *BuildDetails) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *BuildDetails) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *BuildDetails) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *BuildDetails) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BuildDetails) GetArtifactCount() int32 {
	if x != nil {
		return x.ArtifactCount
	}
	return 0
}

func (x *BuildDetails) GetTotalArtifactSizeBytes() int64 {
	if x != nil {
		return x.TotalArtifactSizeBytes
	}
	return 0
}

// ListBuildsRequest is used to request a list of builds with optional filters.
type ListBuildsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by build states
	StateFilter []BuildState `protobuf:"varint,1,rep,packed,name=state_filter,json=stateFilter,proto3,enum=smidr.v1.BuildState" json:"state_filter,omitempty"`
	// Optional time range filter
	TimeRange *TimeStampRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Pagination parameters
	PageSize  int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional customer identifier filter
	Customer string `protobuf:"bytes,5,opt,name=customer,proto3" json:"customer,omitempty"`
	// Include deleted builds in the response
	IncludeDeleted bool `protobuf:"varint,6,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListBuildsRequest) Reset() {
	*x = ListBuildsRequest{}
	mi := &file_builds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsRequest) ProtoMessage() {}

func (x *ListBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsRequest.ProtoReflect.Descriptor instead.
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{4}
}

func (x *ListBuildsRequest) GetStateFilter() []BuildState {
	if x != nil {
		return x.StateFilter
	}
	return nil
}

func (x *ListBuildsRequest) GetTimeRange() *TimeStampRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *ListBuildsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBuildsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListBuildsRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *ListBuildsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

// ListBuildsResponse provides a list of builds matching the request criteria.
type ListBuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*BuildDetails        `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalBuilds   int32                  `protobuf:"varint,3,opt,name=total_builds,json=totalBuilds,proto3" json:"total_builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsResponse) Reset() {
	*x = ListBuildsResponse{}
	mi := &file_builds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsResponse) ProtoMessage() {}

func (x *ListBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsResponse.ProtoReflect.Descriptor instead.
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{5}
}

func (x *ListBuildsResponse) GetBuilds() []*BuildDetails {
	if x != nil {
		return x.Builds
	}
	return nil
}

func (x *ListBuildsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListBuildsResponse) GetTotalBuilds() int32 {
	if x != nil {
		return x.TotalBuilds
	}
	return 0
}

// CancelBuildRequest is used to request the cancellation of a specific build.
type CancelBuildRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuildIdentifier *BuildIdentifier       `protobuf:"bytes,1,opt,name=build_identifier,json=buildIdentifier,proto3" json:"build_identifier,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelBuildRequest) Reset() {
	*x = CancelBuildRequest{}
	mi := &file_builds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBuildRequest) ProtoMessage() {}

func (x *CancelBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBuildRequest.ProtoReflect.Descriptor instead.
func (*CancelBuildRequest) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{6}
}

func (x *CancelBuildRequest) GetBuildIdentifier() *BuildIdentifier {
	if x != nil {
		return x.BuildIdentifier
	}
	return nil
}

// CancelBuildResponse provides the result of a cancellation request.
type CancelBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBuildResponse) Reset() {
	*x = CancelBuildResponse{}
	mi := &file_builds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBuildResponse) ProtoMessage() {}

func (x *CancelBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBuildResponse.ProtoReflect.Descriptor instead.
func (*CancelBuildResponse) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBuildResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelBuildResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetBuildRequest is used to request detailed information about a build.
type GetBuildRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuildIdentifier *BuildIdentifier       `protobuf:"bytes,1,opt,name=build_identifier,json=buildIdentifier,proto3" json:"build_identifier,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBuildRequest) Reset() {
	*x = GetBuildRequest{}
	mi := &file_builds_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildRequest) ProtoMessage() {}

func (x *GetBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildRequest.ProtoReflect.Descriptor instead.
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{8}
}

func (x *GetBuildRequest) GetBuildIdentifier() *BuildIdentifier {
	if x != nil {
		return x.BuildIdentifier
	}
	return nil
}

// DeleteBuildRequest is used to request the deletion of a specific build.
type DeleteBuildRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuildIdentifier *BuildIdentifier       `protobuf:"bytes,1,opt,name=build_identifier,json=buildIdentifier,proto3" json:"build_identifier,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteBuildRequest) Reset() {
	*x = DeleteBuildRequest{}
	mi := &file_builds_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildRequest) ProtoMessage() {}

func (x *DeleteBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildRequest.ProtoReflect.Descriptor instead.
func (*DeleteBuildRequest) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBuildRequest) GetBuildIdentifier() *BuildIdentifier {
	if x != nil {
		return x.BuildIdentifier
	}
	return nil
}

// DeleteBuildResponse provides the result of a deletion request.
type DeleteBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildResponse) Reset() {
	*x = DeleteBuildResponse{}
	mi := &file_builds_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildResponse) ProtoMessage() {}

func (x *DeleteBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildResponse.ProtoReflect.Descriptor instead.
func (*DeleteBuildResponse) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBuildResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBuildResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PurgeBuildsRequest is used to request the purging of old builds.
type PurgeBuildsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Builds older than this timestamp will be purged
	OlderThanUnixSeconds int64 `protobuf:"varint,1,opt,name=older_than_unix_seconds,json=olderThanUnixSeconds,proto3" json:"older_than_unix_seconds,omitempty"`
	// Optional customer identifier filter
	Customer      string `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeBuildsRequest) Reset() {
	*x = PurgeBuildsRequest{}
	mi := &file_builds_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeBuildsRequest) ProtoMessage() {}

func (x *PurgeBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeBuildsRequest.ProtoReflect.Descriptor instead.
func (*PurgeBuildsRequest) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{11}
}

func (x *PurgeBuildsRequest) GetOlderThanUnixSeconds() int64 {
	if x != nil {
		return x.OlderThanUnixSeconds
	}
	return 0
}

func (x *PurgeBuildsRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

// PurgeBuildsResponse provides the result of a purge request.
type PurgeBuildsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PurgedBuildCount int32                  `protobuf:"varint,1,opt,name=purged_build_count,json=purgedBuildCount,proto3" json:"purged_build_count,omitempty"`
	PurgedBuildIds   []string               `protobuf:"bytes,2,rep,name=purged_build_ids,json=purgedBuildIds,proto3" json:"purged_build_ids,omitempty"`
	FreedSpaceBytes  int64                  `protobuf:"varint,3,opt,name=freed_space_bytes,json=freedSpaceBytes,proto3" json:"freed_space_bytes,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PurgeBuildsResponse) Reset() {
	*x = PurgeBuildsResponse{}
	mi := &file_builds_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeBuildsResponse) ProtoMessage() {}

func (x *PurgeBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_builds_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeBuildsResponse.ProtoReflect.Descriptor instead.
func (*PurgeBuildsResponse) Descriptor() ([]byte, []int) {
	return file_builds_proto_rawDescGZIP(), []int{12}
}

func (x *PurgeBuildsResponse) GetPurgedBuildCount() int32 {
	if x != nil {
		return x.PurgedBuildCount
	}
	return 0
}

func (x *PurgeBuildsResponse) GetPurgedBuildIds() []string {
	if x != nil {
		return x.PurgedBuildIds
	}
	return nil
}

func (x *PurgeBuildsResponse) GetFreedSpaceBytes() int64 {
	if x != nil {
		return x.FreedSpaceBytes
	}
	return 0
}

func (x *PurgeBuildsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_builds_proto protoreflect.FileDescriptor

const file_builds_proto_rawDesc = "" +
	"\n" +
	"\fbuilds.proto\x12\bsmidr.v1\x1a\fcommon.proto\"\xe5\x02\n" +
	"\x11StartBuildRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1f\n" +
	"\vforce_clean\x18\x03 \x01(\bR\n" +
	"forceClean\x12.\n" +
	"\x13force_image_rebuild\x18\x04 \x01(\bR\x11forceImageRebuild\x12j\n" +
	"\x15environment_variables\x18\x05 \x03(\v25.smidr.v1.StartBuildRequest.EnvironmentVariablesEntryR\x14environmentVariables\x12\x1a\n" +
	"\bcustomer\x18\x06 \x01(\tR\bcustomer\x1aG\n" +
	"\x19EnvironmentVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x02\n" +
	"\x13BuildStatusResponse\x12D\n" +
	"\x10build_identifier\x18\x01 \x01(\v2\x19.smidr.v1.BuildIdentifierR\x0fbuildIdentifier\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.smidr.v1.BuildStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x128\n" +
	"\n" +
	"timestamps\x18\x06 \x01(\v2\x18.smidr.v1.TimeStampRangeR\n" +
	"timestamps\x12\x1f\n" +
	"\vconfig_path\x18\a \x01(\tR\n" +
	"configPath\x12\x1a\n" +
	"\bcustomer\x18\b \x01(\tR\bcustomer\x12\x18\n" +
	"\adeleted\x18\t \x01(\bR\adeleted\"Z\n" +
	"\x12BuildStatusRequest\x12D\n" +
	"\x10build_identifier\x18\x01 \x01(\v2\x19.smidr.v1.BuildIdentifierR\x0fbuildIdentifier\"\xfe\x06\n" +
	"\fBuildDetails\x12D\n" +
	"\x10build_identifier\x18\x01 \x01(\v2\x19.smidr.v1.BuildIdentifierR\x0fbuildIdentifier\x12\x1a\n" +
	"\bcustomer\x18\x02 \x01(\tR\bcustomer\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12!\n" +
	"\ftarget_image\x18\x04 \x01(\tR\vtargetImage\x12\x18\n" +
	"\amachine\x18\x05 \x01(\tR\amachine\x125\n" +
	"\vbuild_state\x18\x06 \x01(\x0e2\x14.smidr.v1.BuildStateR\n" +
	"buildState\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12'\n" +
	"\x0fbuild_directory\x18\b \x01(\tR\x0ebuildDirectory\x12-\n" +
	"\x12download_directory\x18\t \x01(\tR\x11downloadDirectory\x12$\n" +
	"\x0elog_file_plain\x18\n" +
	" \x01(\tR\flogFilePlain\x12$\n" +
	"\x0elog_file_jsonl\x18\v \x01(\tR\flogFileJsonl\x12\x1f\n" +
	"\vconfig_file\x18\f \x01(\tR\n" +
	"configFile\x12'\n" +
	"\x0fconfig_snapshot\x18\r \x01(\tR\x0econfigSnapshot\x12\x12\n" +
	"\x04user\x18\x0e \x01(\tR\x04user\x12\x12\n" +
	"\x04host\x18\x0f \x01(\tR\x04host\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\x128\n" +
	"\n" +
	"timestamps\x18\x11 \x01(\v2\x18.smidr.v1.TimeStampRangeR\n" +
	"timestamps\x12)\n" +
	"\x10duration_seconds\x18\x12 \x01(\x05R\x0fdurationSeconds\x12\x18\n" +
	"\adeleted\x18\x13 \x01(\bR\adeleted\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x14 \x01(\x03R\tdeletedAt\x12#\n" +
	"\rerror_message\x18\x15 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eartifact_count\x18\x16 \x01(\x05R\rartifactCount\x129\n" +
	"\x19total_artifact_size_bytes\x18\x17 \x01(\x03R\x16totalArtifactSizeBytes\"\x86\x02\n" +
	"\x11ListBuildsRequest\x127\n" +
	"\fstate_filter\x18\x01 \x03(\x0e2\x14.smidr.v1.BuildStateR\vstateFilter\x127\n" +
	"\n" +
	"time_range\x18\x02 \x01(\v2\x18.smidr.v1.TimeStampRangeR\ttimeRange\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12\x1a\n" +
	"\bcustomer\x18\x05 \x01(\tR\bcustomer\x12'\n" +
	"\x0finclude_deleted\x18\x06 \x01(\bR\x0eincludeDeleted\"\x8f\x01\n" +
	"\x12ListBuildsResponse\x12.\n" +
	"\x06builds\x18\x01 \x03(\v2\x16.smidr.v1.BuildDetailsR\x06builds\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12!\n" +
	"\ftotal_builds\x18\x03 \x01(\x05R\vtotalBuilds\"Z\n" +
	"\x12CancelBuildRequest\x12D\n" +
	"\x10build_identifier\x18\x01 \x01(\v2\x19.smidr.v1.BuildIdentifierR\x0fbuildIdentifier\"I\n" +
	"\x13CancelBuildResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x0fGetBuildRequest\x12D\n" +
	"\x10build_identifier\x18\x01 \x01(\v2\x19.smidr.v1.BuildIdentifierR\x0fbuildIdentifier\"Z\n" +
	"\x12DeleteBuildRequest\x12D\n" +
	"\x10build_identifier\x18\x01 \x01(\v2\x19.smidr.v1.BuildIdentifierR\x0fbuildIdentifier\"I\n" +
	"\x13DeleteBuildResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x12PurgeBuildsRequest\x125\n" +
	"\x17older_than_unix_seconds\x18\x01 \x01(\x03R\x14olderThanUnixSeconds\x12\x1a\n" +
	"\bcustomer\x18\x02 \x01(\tR\bcustomer\"\xb3\x01\n" +
	"\x13PurgeBuildsResponse\x12,\n" +
	"\x12purged_build_count\x18\x01 \x01(\x05R\x10purgedBuildCount\x12(\n" +
	"\x10purged_build_ids\x18\x02 \x03(\tR\x0epurgedBuildIds\x12*\n" +
	"\x11freed_space_bytes\x18\x03 \x01(\x03R\x0ffreedSpaceBytes\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\x93\x04\n" +
	"\fBuildService\x12H\n" +
	"\n" +
	"StartBuild\x12\x1b.smidr.v1.StartBuildRequest\x1a\x1d.smidr.v1.BuildStatusResponse\x12M\n" +
	"\x0eGetBuildStatus\x12\x1c.smidr.v1.BuildStatusRequest\x1a\x1d.smidr.v1.BuildStatusResponse\x12G\n" +
	"\n" +
	"ListBuilds\x12\x1b.smidr.v1.ListBuildsRequest\x1a\x1c.smidr.v1.ListBuildsResponse\x12J\n" +
	"\vCancelBuild\x12\x1c.smidr.v1.CancelBuildRequest\x1a\x1d.smidr.v1.CancelBuildResponse\x12=\n" +
	"\bGetBuild\x12\x19.smidr.v1.GetBuildRequest\x1a\x16.smidr.v1.BuildDetails\x12J\n" +
	"\vDeleteBuild\x12\x1c.smidr.v1.DeleteBuildRequest\x1a\x1d.smidr.v1.DeleteBuildResponse\x12J\n" +
	"\vPurgeBuilds\x12\x1c.smidr.v1.PurgeBuildsRequest\x1a\x1d.smidr.v1.PurgeBuildsResponseB\x96\x01\n" +
	"\fcom.smidr.v1B\vBuildsProtoP\x01Z8github.com/schererja/smidr/sdks/pkg/smidr-sdk/v1;smidrv1\xa2\x02\x03SXX\xaa\x02\bSmidr.V1\xca\x02\bSmidr\\V1\xe2\x02\x14Smidr\\V1\\GPBMetadata\xea\x02\tSmidr::V1b\x06proto3"

var (
	file_builds_proto_rawDescOnce sync.Once
	file_builds_proto_rawDescData []byte
)

func file_builds_proto_rawDescGZIP() []byte {
	file_builds_proto_rawDescOnce.Do(func() {
		file_builds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_builds_proto_rawDesc), len(file_builds_proto_rawDesc)))
	})
	return file_builds_proto_rawDescData
}

var file_builds_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_builds_proto_goTypes = []any{
	(*StartBuildRequest)(nil),   // 0: smidr.v1.StartBuildRequest
	(*BuildStatusResponse)(nil), // 1: smidr.v1.BuildStatusResponse
	(*BuildStatusRequest)(nil),  // 2: smidr.v1.BuildStatusRequest
	(*BuildDetails)(nil),        // 3: smidr.v1.BuildDetails
	(*ListBuildsRequest)(nil),   // 4: smidr.v1.ListBuildsRequest
	(*ListBuildsResponse)(nil),  // 5: smidr.v1.ListBuildsResponse
	(*CancelBuildRequest)(nil),  // 6: smidr.v1.CancelBuildRequest
	(*CancelBuildResponse)(nil), // 7: smidr.v1.CancelBuildResponse
	(*GetBuildRequest)(nil),     // 8: smidr.v1.GetBuildRequest
	(*DeleteBuildRequest)(nil),  // 9: smidr.v1.DeleteBuildRequest
	(*DeleteBuildResponse)(nil), // 10: smidr.v1.DeleteBuildResponse
	(*PurgeBuildsRequest)(nil),  // 11: smidr.v1.PurgeBuildsRequest
	(*PurgeBuildsResponse)(nil), // 12: smidr.v1.PurgeBuildsResponse
	nil,                         // 13: smidr.v1.StartBuildRequest.EnvironmentVariablesEntry
	(*BuildIdentifier)(nil),     // 14: smidr.v1.BuildIdentifier
	(BuildState)(0),             // 15: smidr.v1.BuildState
	(*TimeStampRange)(nil),      // 16: smidr.v1.TimeStampRange
}
var file_builds_proto_depIdxs = []int32{
	13, // 0: smidr.v1.StartBuildRequest.environment_variables:type_name -> smidr.v1.StartBuildRequest.EnvironmentVariablesEntry
	14, // 1: smidr.v1.BuildStatusResponse.build_identifier:type_name -> smidr.v1.BuildIdentifier
	15, // 2: smidr.v1.BuildStatusResponse.state:type_name -> smidr.v1.BuildState
	16, // 3: smidr.v1.BuildStatusResponse.timestamps:type_name -> smidr.v1.TimeStampRange
	14, // 4: smidr.v1.BuildStatusRequest.build_identifier:type_name -> smidr.v1.BuildIdentifier
	14, // 5: smidr.v1.BuildDetails.build_identifier:type_name -> smidr.v1.BuildIdentifier
	15, // 6: smidr.v1.BuildDetails.build_state:type_name -> smidr.v1.BuildState
	16, // 7: smidr.v1.BuildDetails.timestamps:type_name -> smidr.v1.TimeStampRange
	15, // 8: smidr.v1.ListBuildsRequest.state_filter:type_name -> smidr.v1.BuildState
	16, // 9: smidr.v1.ListBuildsRequest.time_range:type_name -> smidr.v1.TimeStampRange
	3,  // 10: smidr.v1.ListBuildsResponse.builds:type_name -> smidr.v1.BuildDetails
	14, // 11: smidr.v1.CancelBuildRequest.build_identifier:type_name -> smidr.v1.BuildIdentifier
	14, // 12: smidr.v1.GetBuildRequest.build_identifier:type_name -> smidr.v1.BuildIdentifier
	14, // 13: smidr.v1.DeleteBuildRequest.build_identifier:type_name -> smidr.v1.BuildIdentifier
	0,  // 14: smidr.v1.BuildService.StartBuild:input_type -> smidr.v1.StartBuildRequest
	2,  // 15: smidr.v1.BuildService.GetBuildStatus:input_type -> smidr.v1.BuildStatusRequest
	4,  // 16: smidr.v1.BuildService.ListBuilds:input_type -> smidr.v1.ListBuildsRequest
	6,  // 17: smidr.v1.BuildService.CancelBuild:input_type -> smidr.v1.CancelBuildRequest
	8,  // 18: smidr.v1.BuildService.GetBuild:input_type -> smidr.v1.GetBuildRequest
	9,  // 19: smidr.v1.BuildService.DeleteBuild:input_type -> smidr.v1.DeleteBuildRequest
	11, // 20: smidr.v1.BuildService.PurgeBuilds:input_type -> smidr.v1.PurgeBuildsRequest
	1,  // 21: smidr.v1.BuildService.StartBuild:output_type -> smidr.v1.BuildStatusResponse
	1,  // 22: smidr.v1.BuildService.GetBuildStatus:output_type -> smidr.v1.BuildStatusResponse
	5,  // 23: smidr.v1.BuildService.ListBuilds:output_type -> smidr.v1.ListBuildsResponse
	7,  // 24: smidr.v1.BuildService.CancelBuild:output_type -> smidr.v1.CancelBuildResponse
	3,  // 25: smidr.v1.BuildService.GetBuild:output_type -> smidr.v1.BuildDetails
	10, // 26: smidr.v1.BuildService.DeleteBuild:output_type -> smidr.v1.DeleteBuildResponse
	12, // 27: smidr.v1.BuildService.PurgeBuilds:output_type -> smidr.v1.PurgeBuildsResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_builds_proto_init() }
func file_builds_proto_init() {
	if File_builds_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_builds_proto_rawDesc), len(file_builds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_builds_proto_goTypes,
		DependencyIndexes: file_builds_proto_depIdxs,
		MessageInfos:      file_builds_proto_msgTypes,
	}.Build()
	File_builds_proto = out.File
	file_builds_proto_goTypes = nil
	file_builds_proto_depIdxs = nil
}
