// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common.proto

package smidrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildState int32

const (
	BuildState_BUILD_STATE_UNSPECIFIED          BuildState = 0
	BuildState_BUILD_STATE_QUEUED               BuildState = 1
	BuildState_BUILD_STATE_PREPARING            BuildState = 2
	BuildState_BUILD_STATE_BUILDING             BuildState = 3
	BuildState_BUILD_STATE_EXTRACTING_ARTIFACTS BuildState = 4
	BuildState_BUILD_STATE_COMPLETED            BuildState = 5
	BuildState_BUILD_STATE_FAILED               BuildState = 6
	BuildState_BUILD_STATE_CANCELLED            BuildState = 7
)

// Enum value maps for BuildState.
var (
	BuildState_name = map[int32]string{
		0: "BUILD_STATE_UNSPECIFIED",
		1: "BUILD_STATE_QUEUED",
		2: "BUILD_STATE_PREPARING",
		3: "BUILD_STATE_BUILDING",
		4: "BUILD_STATE_EXTRACTING_ARTIFACTS",
		5: "BUILD_STATE_COMPLETED",
		6: "BUILD_STATE_FAILED",
		7: "BUILD_STATE_CANCELLED",
	}
	BuildState_value = map[string]int32{
		"BUILD_STATE_UNSPECIFIED":          0,
		"BUILD_STATE_QUEUED":               1,
		"BUILD_STATE_PREPARING":            2,
		"BUILD_STATE_BUILDING":             3,
		"BUILD_STATE_EXTRACTING_ARTIFACTS": 4,
		"BUILD_STATE_COMPLETED":            5,
		"BUILD_STATE_FAILED":               6,
		"BUILD_STATE_CANCELLED":            7,
	}
)

func (x BuildState) Enum() *BuildState {
	p := new(BuildState)
	*p = x
	return p
}

func (x BuildState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildState) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (BuildState) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x BuildState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildState.Descriptor instead.
func (BuildState) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type BuildIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildIdentifier) Reset() {
	*x = BuildIdentifier{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildIdentifier) ProtoMessage() {}

func (x *BuildIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildIdentifier.ProtoReflect.Descriptor instead.
func (*BuildIdentifier) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *BuildIdentifier) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type TimeStampRange struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StartTimeUnixSeconds int64                  `protobuf:"varint,1,opt,name=start_time_unix_seconds,json=startTimeUnixSeconds,proto3" json:"start_time_unix_seconds,omitempty"`
	EndTimeUnixSeconds   int64                  `protobuf:"varint,2,opt,name=end_time_unix_seconds,json=endTimeUnixSeconds,proto3" json:"end_time_unix_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TimeStampRange) Reset() {
	*x = TimeStampRange{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeStampRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeStampRange) ProtoMessage() {}

func (x *TimeStampRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeStampRange.ProtoReflect.Descriptor instead.
func (*TimeStampRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *TimeStampRange) GetStartTimeUnixSeconds() int64 {
	if x != nil {
		return x.StartTimeUnixSeconds
	}
	return 0
}

func (x *TimeStampRange) GetEndTimeUnixSeconds() int64 {
	if x != nil {
		return x.EndTimeUnixSeconds
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\bsmidr.v1\",\n" +
	"\x0fBuildIdentifier\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"z\n" +
	"\x0eTimeStampRange\x125\n" +
	"\x17start_time_unix_seconds\x18\x01 \x01(\x03R\x14startTimeUnixSeconds\x121\n" +
	"\x15end_time_unix_seconds\x18\x02 \x01(\x03R\x12endTimeUnixSeconds*\xea\x01\n" +
	"\n" +
	"BuildState\x12\x1b\n" +
	"\x17BUILD_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BUILD_STATE_QUEUED\x10\x01\x12\x19\n" +
	"\x15BUILD_STATE_PREPARING\x10\x02\x12\x18\n" +
	"\x14BUILD_STATE_BUILDING\x10\x03\x12$\n" +
	" BUILD_STATE_EXTRACTING_ARTIFACTS\x10\x04\x12\x19\n" +
	"\x15BUILD_STATE_COMPLETED\x10\x05\x12\x16\n" +
	"\x12BUILD_STATE_FAILED\x10\x06\x12\x19\n" +
	"\x15BUILD_STATE_CANCELLED\x10\aB\x96\x01\n" +
	"\fcom.smidr.v1B\vCommonProtoP\x01Z8github.com/schererja/smidr/sdks/pkg/smidr-sdk/v1;smidrv1\xa2\x02\x03SXX\xaa\x02\bSmidr.V1\xca\x02\bSmidr\\V1\xe2\x02\x14Smidr\\V1\\GPBMetadata\xea\x02\tSmidr::V1b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(BuildState)(0),         // 0: smidr.v1.BuildState
	(*BuildIdentifier)(nil), // 1: smidr.v1.BuildIdentifier
	(*TimeStampRange)(nil),  // 2: smidr.v1.TimeStampRange
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
