// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: smidr_service.proto

package smidrv1

import (
	_ "github.com/schererja/smidr-protos/gen/go/smidr/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_smidr_service_proto protoreflect.FileDescriptor

const file_smidr_service_proto_rawDesc = "" +
	"\n" +
	"\x13smidr_service.proto\x12\bsmidr.v1\x1a\fbuilds.proto\x1a\x0fartifacts.proto\x1a\n" +
	"logs.protoB\x97\x01\n" +
	"\fcom.smidr.v1B\x11SmidrServiceProtoP\x01Z3github.com/schererja/smidr/sdks/go/smidr/v1;smidrv1\xa2\x02\x03SXX\xaa\x02\bSmidr.V1\xca\x02\bSmidr\\V1\xe2\x02\x14Smidr\\V1\\GPBMetadata\xea\x02\tSmidr::V1b\x06proto3"

var file_smidr_service_proto_goTypes = []any{}
var file_smidr_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smidr_service_proto_init() }
func file_smidr_service_proto_init() {
	if File_smidr_service_proto != nil {
		return
	}
	file_builds_proto_init()
	file_logs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smidr_service_proto_rawDesc), len(file_smidr_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_smidr_service_proto_goTypes,
		DependencyIndexes: file_smidr_service_proto_depIdxs,
	}.Build()
	File_smidr_service_proto = out.File
	file_smidr_service_proto_goTypes = nil
	file_smidr_service_proto_depIdxs = nil
}
