package init

import (
	"fmt"
	"log/slog"
	"os"

	"github.com/intrik8-labs/smidr/internal/logging"
	"github.com/spf13/cobra"
)

var log *logging.Logger

var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a new Smidr project configuration",
	Long: `Initialize a new Smidr project by generating a template configuration file (smidr.yaml) in the current directory.

If a project name is provided, it will be used in the generated config. If not, 'my-smidr-project' is used by default.

This command will not overwrite an existing smidr.yaml file.`,
	Example: `  smidr init
  smidr init myproject
  smidr init "Acme IoT Gateway"`,
	Args: cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		projectName := "my-smidr-project"
		if len(args) == 1 {
			projectName = args[0]
		}
		if err := initProject(projectName); err != nil {
			log.Error("Error initializing project", slog.String("error", err.Error()))
			return
		}
	},
}

// New returns the init command for registration with the root command
func New(logger *logging.Logger) *cobra.Command {
	if logger == nil {
		logger = logging.Default()
	}
	log = logger
	return initCmd
}

func initProject(projectName string) error {
	configPath := "smidr.yaml"
	if _, err := os.Stat("smidr.yaml"); err == nil {
		return fmt.Errorf("configuration file %s already exists", configPath)
	}

	// Create the template file
	template := generateConfigTemplate(projectName)
	if err := os.WriteFile(configPath, []byte(template), 0644); err != nil {
		return fmt.Errorf("failed to write configuration file: %w", err)
	}
	log.Info("Initialized Smidr project", slog.String("projectName", projectName))
	log.Info("Edit smidr.yaml to configure your build")
	log.Info("Run 'smidr build' to start building")
	return nil
}

func generateConfigTemplate(projectName string) string {
	return fmt.Sprintf(`# Smidr Agent Configuration
# Generated by 'smidr init %s'

agent:
  # Unique agent identifier. Leave empty to auto-generate and persist to id_file.
  id: "%s"

  # File path where the agent ID is persisted when generated.
  id_file: "~/.config/smidr/agent-id"

  # Demo mode uses in-memory execution; do not use in production.
  demo: false

control_plane:
  # Control plane base URI (e.g., https://api.smidr.dev)
  uri: "https://api.smidr.dev"

runtime:
  # Working directory for builds and artifacts.
  work_dir: "~/.local/share/smidr"
`, projectName, projectName)
}
