// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: logs.proto

package smidrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamBuildLogsRequest is used to request streaming logs for a build.
type StreamBuildLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the build whose logs are to be streamed.
	BuildIdentifier *BuildIdentifier `protobuf:"bytes,1,opt,name=build_identifier,json=buildIdentifier,proto3" json:"build_identifier,omitempty"`
	// If true, continue streaming new logs as they are generated.
	Follow        bool `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBuildLogsRequest) Reset() {
	*x = StreamBuildLogsRequest{}
	mi := &file_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBuildLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBuildLogsRequest) ProtoMessage() {}

func (x *StreamBuildLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBuildLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamBuildLogsRequest) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{0}
}

func (x *StreamBuildLogsRequest) GetBuildIdentifier() *BuildIdentifier {
	if x != nil {
		return x.BuildIdentifier
	}
	return nil
}

func (x *StreamBuildLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp of the log entry in Unix seconds.
	TimestampUnixSeconds int64 `protobuf:"varint,1,opt,name=timestamp_unix_seconds,json=timestampUnixSeconds,proto3" json:"timestamp_unix_seconds,omitempty"`
	// The actual log message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Log level (e.g., INFO, WARN, ERROR).
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// Source of the log entry (e.g., build step name).
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// Which stream the log belongs to (e.g., stdout, stderr).
	Stream        string `protobuf:"bytes,5,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetTimestampUnixSeconds() int64 {
	if x != nil {
		return x.TimestampUnixSeconds
	}
	return 0
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

var File_logs_proto protoreflect.FileDescriptor

const file_logs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"logs.proto\x12\bsmidr.v1\x1a\fcommon.proto\"v\n" +
	"\x16StreamBuildLogsRequest\x12D\n" +
	"\x10build_identifier\x18\x01 \x01(\v2\x19.smidr.v1.BuildIdentifierR\x0fbuildIdentifier\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"\xa0\x01\n" +
	"\bLogEntry\x124\n" +
	"\x16timestamp_unix_seconds\x18\x01 \x01(\x03R\x14timestampUnixSeconds\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\tR\x06stream2W\n" +
	"\n" +
	"LogService\x12I\n" +
	"\x0fStreamBuildLogs\x12 .smidr.v1.StreamBuildLogsRequest\x1a\x12.smidr.v1.LogEntry0\x01B\x8f\x01\n" +
	"\fcom.smidr.v1B\tLogsProtoP\x01Z3github.com/schererja/smidr/sdks/go/smidr/v1;smidrv1\xa2\x02\x03SXX\xaa\x02\bSmidr.V1\xca\x02\bSmidr\\V1\xe2\x02\x14Smidr\\V1\\GPBMetadata\xea\x02\tSmidr::V1b\x06proto3"

var (
	file_logs_proto_rawDescOnce sync.Once
	file_logs_proto_rawDescData []byte
)

func file_logs_proto_rawDescGZIP() []byte {
	file_logs_proto_rawDescOnce.Do(func() {
		file_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)))
	})
	return file_logs_proto_rawDescData
}

var file_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_logs_proto_goTypes = []any{
	(*StreamBuildLogsRequest)(nil), // 0: smidr.v1.StreamBuildLogsRequest
	(*LogEntry)(nil),               // 1: smidr.v1.LogEntry
	(*BuildIdentifier)(nil),        // 2: smidr.v1.BuildIdentifier
}
var file_logs_proto_depIdxs = []int32{
	2, // 0: smidr.v1.StreamBuildLogsRequest.build_identifier:type_name -> smidr.v1.BuildIdentifier
	0, // 1: smidr.v1.LogService.StreamBuildLogs:input_type -> smidr.v1.StreamBuildLogsRequest
	1, // 2: smidr.v1.LogService.StreamBuildLogs:output_type -> smidr.v1.LogEntry
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_logs_proto_init() }
func file_logs_proto_init() {
	if File_logs_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_proto_rawDesc), len(file_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_proto_goTypes,
		DependencyIndexes: file_logs_proto_depIdxs,
		MessageInfos:      file_logs_proto_msgTypes,
	}.Build()
	File_logs_proto = out.File
	file_logs_proto_goTypes = nil
	file_logs_proto_depIdxs = nil
}
