package init

import (
	"fmt"
	"log/slog"
	"os"

	"github.com/schererja/smidr/pkg/logger"
	"github.com/spf13/cobra"
)

var log *logger.Logger

var initCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a new Smidr project configuration",
	Long: `Initialize a new Smidr project by generating a template configuration file (smidr.yaml) in the current directory.

If a project name is provided, it will be used in the generated config. If not, 'my-smidr-project' is used by default.

This command will not overwrite an existing smidr.yaml file.`,
	Example: `  smidr init
  smidr init myproject
  smidr init "Acme IoT Gateway"`,
	Args: cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		projectName := "my-smidr-project"
		if len(args) == 1 {
			projectName = args[0]
		}
		if err := initProject(projectName); err != nil {
			log.Error("Error initializing project", err)
			return
		}
	},
}

// New returns the init command for registration with the root command
func New(logger *logger.Logger) *cobra.Command {
	log = logger
	return initCmd
}

func initProject(projectName string) error {
	configPath := "smidr.yaml"
	if _, err := os.Stat("smidr.yaml"); err == nil {
		return fmt.Errorf("configuration file %s already exists", configPath)
	}

	// Create the template file
	template := generateConfigTemplate(projectName)
	if err := os.WriteFile(configPath, []byte(template), 0644); err != nil {
		return fmt.Errorf("failed to write configuration file: %w", err)
	}
	log.Info("Initialized Smidr project", slog.String("projectName", projectName))
	log.Info("Edit smidr.yaml to configure your build")
	log.Info("Run 'smidr build' to start building")
	return nil
}

func generateConfigTemplate(projectName string) string {
	return fmt.Sprintf(`# Smidr Build Configuration
# Generated by 'smidr init %s'

name: %s
description: "Custom embedded Linux image"

# Yocto version to use
yocto_series: kirkstone

# Base configuration - REQUIRED
base:
  # Choose a provider that matches your hardware:
  # - "poky" for generic x86/ARM (start here for learning)
  # - "toradex" for Toradex modules
  # - "raspberrypi" for Raspberry Pi boards
  provider: poky

  # Machine to build for (use qemux86-64 for quick testing)
  machine: qemux86-64

  # Distribution (usually "poky" is fine)
  distro: poky

  # Version matching your yocto_series
  version: "6.0.0"

# Layers - REQUIRED (minimal Poky layers for a basic build)
layers:
  - name: poky
    git: "https://git.yoctoproject.org/poky"

  # Uncomment for OpenEmbedded recipes (e.g., python3, vim, etc.)
  # - name: meta-openembedded
  #   git: "https://git.openembedded.org/meta-openembedded"

  # Add more layers as needed for your hardware:
  # Toradex boards:
  # - name: meta-freescale
  #   git: "https://github.com/Freescale/meta-freescale.git"
  #   branch: kirkstone
  # - name: meta-freescale-3rdparty
  #   git: "https://github.com/Freescale/meta-freescale-3rdparty.git"
  #   branch: kirkstone
  # - name: meta-toradex-bsp-common
  #   git: "https://git.toradex.com/meta-toradex-bsp-common.git"
  # - name: meta-toradex-nxp
  #   git: "https://git.toradex.com/meta-toradex-nxp.git"

  # Raspberry Pi:
  # - name: meta-raspberrypi
  #   git: "https://git.yoctoproject.org/meta-raspberrypi"

  # Custom/local layers:
  # - name: meta-mycompany
  #   path: ../meta-mycompany

# Build configuration - REQUIRED
build:
  # Image to build (core-image-minimal is smallest)
  image: core-image-minimal

  # Must match base.machine above
  machine: qemux86-64

  # Packages to add to the image (requires meta-openembedded layer)
  # extra_packages:
  #   - python3
  #   - vim
  #   - openssh

  # Build performance (adjust based on your system)
  # parallel_make: 4
  # bb_number_threads: 4

# Files to extract after build completes
# artifacts:
#   - "*.wic"           # Disk images
#   - "*.tar.bz2"       # Root filesystem
#   - "*-sdk-*.sh"      # SDK installer

# Advanced: Override default directories
# directories:
#   downloads: ~/.smidr/downloads
#   layers: ~/.smidr/layers
#   sstate: ~/.smidr/sstate-cache

# Advanced: Container resource limits
# container:
#   memory: "8g"
#   cpu_count: 4
`, projectName, projectName)
}
