<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.60.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.60.0" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="13.9.0" />
    <PackageReference Include="HotChocolate.Data" Version="13.9.0" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="13.9.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\Smidr.ControlPlane.Application\Smidr.ControlPlane.Application.csproj" />
    <ProjectReference
      Include="..\Smidr.ControlPlane.Infrastructure\Smidr.ControlPlane.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Generated\*.cs" Link="Generated\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>