name: Toradex Integration Build

on:
  workflow_dispatch:
    inputs:
      force_clean_build:
        description: "Force clean build (--clean flag) to generate artifacts"
        required: false
        type: boolean
        default: false
  schedule:
    # Weekly on Mondays at 03:00 UTC
    - cron: "0 3 * * 1"

jobs:
  build-toradex:
    runs-on: self-hosted
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.1"

      - name: Go build
        run: go build -v ./...

      - name: Ensure Docker is available
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker not found on self-hosted runner" >&2
            exit 1
          fi
          docker info

      - name: Run Toradex integration build (core-image-minimal)
        env:
          YOCTO_DL_DIR: ~/.smidr/downloads
          YOCTO_SSTATE_DIR: ~/.smidr/sstate
          YOCTO_TMP_DIR: ~/.smidr/tmp
          YOCTO_DEPLOY_DIR: ~/.smidr/deploy
        run: |
          # Note: When build completes 100% from sstate cache (common on repeated runs),
          # no deploy artifacts are generated. This is expected and validates build reproducibility.
          # The sstate cache itself serves as the cryptographically-verified artifact store.
          # Use workflow input 'force_clean_build' to regenerate only image artifacts (fast)

          CLEAN_FLAG=""
          if [ "${{ github.event.inputs.force_clean_build }}" = "true" ]; then
            echo "🧹 Clean image build requested - will regenerate image artifacts only"
            CLEAN_FLAG="--clean-image"
          fi

          go run ./cmd/smidr --config smidr-toradex-ci.yaml build --customer ci-toradex $CLEAN_FLAG

      - name: List artifacts for Toradex build
        run: |
          ls -la ~/.smidr/artifacts || true

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: toradex-build-logs
          path: |
            ~/.smidr/builds/**/build-log.txt
            ~/.smidr/builds/**/build-log.jsonl
          if-no-files-found: warn

      - name: Upload deploy artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: toradex-deploy
          path: |
            ~/.smidr/artifacts/**/deploy/**
          if-no-files-found: warn
